### ISSUE TITLE
LLVM mislinks some constructors

### ISSUE THREAD

**Issue by salos1982** [kripken/emscripten#4234] opened 2016-04-08 07:48 UTC
1.35 version does not have such issue. I tested on 1.36.1 and master verisons.
[testEmcc1.36.zip](https://github.com/kripken/emscripten/files/209799/testEmcc1.36.zip)

compile with command 
`emcc -std=c++11 @files.list -o test.js`
there is warning 
**warning: unresolved symbol: _ZN16CPlayerEquipmentD2Ev**
but destructor ~CPlayerEquipment exists. Visual Studio compile well.

**Comment by NuclearCookie** [comment] 2016-04-08 08:02
I have a similar issue with the current master. ( 1.36 ). For me this issue only happens in a debug build.

**Comment by kripken** [comment] 2016-04-08 21:10
This goes into C++ abi issues that are way above my understanding. But this is what happens here. The crucial part is the virtual destructor `CPlayerEquipment`. if you build the Armor, PlayerEquipment and Sword cpp files into .o files, then link them, then the order of linking matters. PlayerEquipment defines the virtual destructor to `CPlayerEquipment`, which is used by the other two files. If both are before, or both are after, all is well. But if PlayerEquipment is in the middle, the first linking renames the symbol, to `_ZN16CPlayerEquipmentD2Ev.3` (note `.3` suffix). Then things go wrong, as the last file wants the original name.

You can avoid the issue by defining the virtual destructor (which is empty anyhow) in the header file. Then it gets marked as weakly linked, and everyone is happy. Doing it in the header is pretty common, so I suspect that's why this problem isn't hit more often?

No idea if this is a bug in llvm-link (which links that way), or in clang (which decides what to mark weak, etc.). Might be best to file this reduced test case for LLVM (just those 3 files are enough to show the issue, and the steps to reproduce are just to link the in different orders and look at llvm-nm | grep that symbol).

cc @sunfishcode, maybe this rings a bell for you?

**Comment by sunfishcode** [comment] 2016-04-08 21:33
The `.3` suffix sounds like something llvm-link would use if it encounterd two definitions of _ZN16CPlayerEquipmentD2Ev and wanted to keep both. However, it's not clear why it would be encountering multiple _ZN16CPlayerEquipmentD2Ev definitions here.

**Comment by kripken** [comment] 2016-04-08 21:40
Yeah, there aren't multiple ones. This sounds like an llvm-link bug then? Here is what's going on in more detail, with just 2 files:

````
$ llvm-nm Armor.o | grep _ZN16CPlayerEquipmentD2Ev
         U _ZN16CPlayerEquipmentD2Ev

$ llvm-nm PlayerEquipment.o | grep _ZN16CPlayerEquipmentD2Ev
-------- T _ZN16CPlayerEquipmentD2Ev

$ llvm-link -o all.bc Armor.o  PlayerEquipment.o ; llvm-nm all.bc | grep _ZN16CPlayerEquipmentD2Ev
-------- T _ZN16CPlayerEquipmentD2Ev.3
````

That is, Armor has it as undefined, PlayerEquipment has it as defined, but linking the two renames it to `*.3`. It's as if it's pre-emptively trying to avoid a collision?

**Comment by sunfishcode** [comment] 2016-04-09 00:14
Yes, that sounds like an llvm-link bug.

**Comment by benvanik** [comment] 2016-04-18 21:36
Seeing the same thing here in 1.36 :(
Does not reproduce with tip-of-tree LLVM in non-emscripten/non-fastcomp configurations, even if command line is the same.

**Comment by kripken** [comment] 2016-04-18 22:10
Did you try with the same libc, headers, etc. - i.e., just changing the triple? Or did you replace emcc commands with clang commands?

If that fails in the former mode, then it suggests this is a bug which has been since fixed by LLVM, and would get fixed for us with an LLVM update. Otherwise, that would be puzzling.

**Comment by AlexPerrot** [comment] 2016-04-29 15:17
I have a similar problem when building cppunit.

I have tested with the included files and tried to do some bisecting.
The bug occurs in version 1.35.20, but not in version 1.35.18.

Hope this can help !

**Comment by marcounity** [comment] 2016-05-02 15:32
We also experienced a missing constructor in our code and we fixed it by moving the implementation to the header file.

**Comment by juj** [comment] 2016-05-18 12:41
Hey, any updates here? Is this reported in LLVM side? @kripken: If this might be fixed in LLVM tip, I wonder if it would be possible to merge us up?

**Comment by kripken** [comment] 2016-05-18 16:18
I'm not aware of any updates not mentioned in this issue. Current status is we need to verify if it's a bug upstream or if it was fixed already (see https://github.com/kripken/emscripten/issues/4234#issuecomment-211601473).

**Comment by Krelborn** [comment] 2016-05-24 10:06
Having the same problem using 1.36.x versions of the SDK after upgrading from 1.35.0. It looks like changing the order of linking so parent classes are listed after their subclasses fixes the issue problem for me.

I'm trying to fix the order in my CMake file at the minute to resolve this but the codebase is very large so this might be difficult.

Any idea what the cause is yet or if there's a better workaround than just changing the order of object files passed to emcc?

**Comment by AlexPerrot** [comment] 2016-05-26 16:13
I have tested a little more to tackle this issue.
It only happens if using `-O0` optimization level.
`-O1` and `-O2` work fine.
You can test that with the code from the OP.

**Comment by tarun550** [comment] 2016-06-15 09:15
Had the same issue and @AlexPerrot 's solution seems to work for me.
As reported earlier this was not an issue with 1.35

**Comment by kripken** [comment] 2016-08-05 17:01
A new merge from upstream LLVM is happening soon (#4460), which might help here. Would be cool if someone tested to check.

**Comment by kripken** [comment] 2016-08-06 00:13
Good news, indeed in the new LLVM merge in preparation the testcase in the first comment in this bug no longer reproduces, so I guess upstream fixed things.

**Comment by kripken** [comment] 2016-08-09 04:02
Upstream merge has landed on incoming, so this should now be resolved.

**Closed by kripken** 2016-08-09 04:02 UTC

**Comment by juj** [comment] 2016-08-16 17:59
Btw, the ctor/dtor mislinking issue is something that would be nice to get in the test suite, given that it bit so many developers and I don't think we had a test that would have exposed it in the suite? I wonder if anyone might have a tiny small test case to add to the test suite?
