### ISSUE TITLE
Some places still eval() when -s NO_DYNAMIC_EXECUTION=1 is set.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3882] opened 2015-10-27 17:20 UTC
There are still call sites left that call `eval()` even when `-s NO_DYNAMIC_EXECUTION=1` is specified. Such places include
    - `dlopen`: https://github.com/kripken/emscripten/blob/incoming/src/library.js#L1532
    - `emscripten_run_script`: https://github.com/kripken/emscripten/blob/incoming/src/library.js#L3711
    - `emscripten_run_script_int`: https://github.com/kripken/emscripten/blob/incoming/src/library.js#L3715
    - `emscripten_run_script_string`: https://github.com/kripken/emscripten/blob/incoming/src/library.js#L3718
    - `Runtime.loadDynamicLibrary`: https://github.com/kripken/emscripten/blob/master/src/runtime.js#L309
    - file packager loader: https://github.com/kripken/emscripten/blob/master/tools/file_packager.py#L180

I'm running into problems with the last one specifically, where when I specify -s NO_DYNAMIC_EXECUTION=1, the generated code still eval()s in the file package. Are there ways to avoid `eval()`ing in any of these completely?

I suppose some of these could be using `globalEval()` instead of `eval()`, although that  probably doesn't help anything, since that would just shift the error message from being a browser-generated message to one that we generate. Instead, we should patch up so that more of these places would become compiler errors or warnings, i.e. if `-s NO_DYNAMIC_EXECUTION=1` is specified and we don't have a way to generate code that satisfies this, a diagnostic would be emitted.

**Comment by kripken** [comment] 2015-10-28 00:30
That last one only shows up in the source code when closure compiler is enabled. Does it with with closure disabled?

Perhaps we should give an error on closure + `NO_DYNAMIC_EXECUTION`, since it can't work...

**Comment by kripken** [comment] 2015-10-28 00:31
Oh, when running the file packager directly, one needs `--no-closure` to tell it closure is not being run on the main file.

**Comment by juj** [comment] 2015-10-28 11:19
Yeah, passed `--no-closure` to file packager to make it not eval. Do we need an `eval()`ing construct to be generated in file packager in general? Or would there be some other way to figure out the `Module` object?

**Comment by kripken** [comment] 2015-10-28 17:19
Not sure I understand the question, but we only need it there for the closure compiler case. Closure would minify the `Module` name itself.

I think we could default in the file packager to having that off, actually - so only people using closure would need to add a flag.

**Comment by juj** [comment] 2015-11-02 12:13
Hmm no, I'm not sure if that would help much. I suppose I was hoping that the evals would not be strictly necessary in these call sites, and we'd have a functionally identical way to achieve the same with some other constructs, but perhaps that can't be the case here(?)

**Comment by kripken** [comment] 2015-11-02 21:10
There might be. But first - do you actually need closure, which is the cause of the last one?

**Comment by juj** [comment] 2015-11-02 21:25
No, closure was not needed, so I was able to work around that instance by passing `--no-closure` to where the file packager was manually invoked.

**Comment by kripken** [comment] 2015-11-02 21:28
Ok. Looking at the others:

 * dlopen and loadDynamicLibrary: has to eval. the module is in text format.
 * run_script: has to eval. it receives a string to execute (often EM_ASM can be used instead, unless the string is dynamically constructed)

**Comment by kripken** [comment] 2015-11-23 18:49
Resolved by that pull.

**Closed by kripken** 2015-11-23 18:49 UTC
