### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by cissusnar** [kripken/emscripten#5292] opened 2017-06-12 03:01 UTC
![2017-06-12 11 01 00](https://user-images.githubusercontent.com/2087003/27017884-860daa44-4f5e-11e7-9275-65d9a1b67f98.png)

**Comment by juj** [comment] 2017-06-13 11:26
Thanks for reporting. This is a duplicate of #5291 and #5272, and is now fixed. Both `emsdk install latest` and `emsdk install sdk-1.37.13-64bit` should now work.

However while working on this, I noticed that it's possible that emsdk update returns without printing anything and does not actually update emsdk. If that is the case, try redownloading emsdk_portable from a zip file (https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.zip for Windows and https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz for OS X)

If the issue still appears with latest, feel free to reopen.

**Closed by juj** 2017-06-13 11:26 UTC
