### ISSUE TITLE
pthread_mutex_lock crashes after recent musl update

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [kripken/emscripten#5038] opened 2017-03-15 21:24 UTC
Crash happens at this line:
https://github.com/kripken/emscripten/blob/abf5add3c36d80804b9eff8057dacc391070cc15/system/lib/libc/musl/src/thread/pthread_mutex_trylock.c#L40

`robust_list.head` is set to 0, but should be set to `&new->robust_list.head` for the empty list, like here in the normal version of pthread_create:
https://github.com/kripken/emscripten/blob/abf5add3c36d80804b9eff8057dacc391070cc15/system/lib/libc/musl/src/thread/pthread_create.c#L269

Should be a trivial fix. Summoning @juj.

**Comment by kripken** [comment] 2017-03-15 22:24
Also cc @jgravelle-google who did the musl update.

Sounds like we need a new test for this, as it wasn't caught?

**Comment by jgravelle-google** [comment] 2017-03-16 17:32
Stuff that I've found from investigating so far:
So the emscripten buildbots show some pthread test breakage from before the musl update, that I can't reproduce locally.
Said breakage was introduced in ubuntu build 214 (http://clb.demon.fi:8112/#/builders/4/builds/214/steps/9/logs/stdio), which was commit https://github.com/kripken/emscripten/commit/28d43cc84b739bd3011f4768f9e2fed8c8a2000a which was almost certainly unrelated.
... Looking more closely, the buildbots test against Firefox Stable, where I've been testing with Nightly. The test was ran on March 8th, which was when Firefox 52 came out, which changed its support for asm.js atomics, explaining the breakage. (Testing locally with Firefox 52 is able to reproduce that breakage).
 
Those tests aren't related to `pthread_mutex_lock`, but are the only thing I can see going wrong with pthreads, meaning our tests are somehow insufficient.
We currently call `pthread_mutex_lock` from a few tests, most notably to me looks like `test_pthread_mutex.cpp`.
@OleksandrChekhovskyi , do you have a reproducing case? Is there a project we can build or other input code? What browser were you testing in? Thanks!

**Comment by OleksandrChekhovskyi** [comment] 2017-03-16 19:30
Clarification: it's this kind of mutex that seems to crash reliably:
```
pthread_mutexattr_t attr;
pthread_mutexattr_init(&attr);
pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
pthread_mutex_init(&lock, &attr);
```
I have tried modifying `test_pthread_mutex.cpp` to use this attribute, and got the same crash I'm getting in my real code.

**Comment by juj** [comment] 2017-03-17 15:48
Taking...

**Comment by juj** [comment] 2017-03-17 16:04
Fixed in above commit, thanks for reporting!

**Closed by juj** 2017-03-17 16:04 UTC
Labels: multithreading
