### ISSUE TITLE
emcc error when building with OUTLINING_LIMIT

### ISSUE THREAD

**Issue by bgrins** [kripken/emscripten#3297] opened 2015-04-01 01:56 UTC
I bumped into this error when compiling [this project](https://github.com/bgrins/videoconverter.js) with an outlining limit set.  Here are STR:

1) Download https://www.dropbox.com/s/sce8kzxuu2i47g3/emscripten-testcase.zip?dl=0
2) Run: `~/bin/emsdk_portable/emscripten/1.29.0/emcc -s OUTLINING_LIMIT=100000 -s VERBOSE=1 -s TOTAL_MEMORY=33554432 -O2 -v ffmpeg.bc libx264.bc  libvpx.bc libz.bc -o ffmpeg-all-codecs.js --pre-js ffmpeg_pre.js --post-js ffmpeg_post.js`

I see this error:

    Stack: Error
        at assertTrue (eval at globalEval (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:111:8), <anonymous>:59:26)
        at ~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:2479:7
        at traverse (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:212:18)
        at traverseChildren (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:190:23)
        at traverse (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:217:9)
        at traverseChildren (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:190:23)
        at traverse (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:217:9)
        at traverseChildren (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:190:23)
        at traverse (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:217:9)
        at traverseChildren (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:190:23)
        at traverse (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:217:9)
        at getStackBumpNode (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:2475:3)
        at getStackBumpSize (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:2488:14)
        at analyzeFunction (~/bin/emsdk_portable/emscripten/1.29.0/tools/js-optimizer.js:5279:21)

    undefined:60
        throw msg;
              ^
    Assertion failed: undefined
    Traceback (most recent call last):
      File "~/bin/emsdk_portable/emscripten/1.29.0/emcc", line 1529, in <module>
        flush_js_optimizer_queue()
      File "~/bin/emsdk_portable/emscripten/1.29.0/emcc", line 1438, in flush_js_optimizer_queue
        run_passes(chunks[i], 'js_opts_' + str(i), just_split='receiveJSON' in chunks[i], just_concat='emitJSON' in chunks[i])
      File "~/bin/emsdk_portable/emscripten/1.29.0/emcc", line 1409, in run_passes
        final = shared.Building.js_optimizer(final, passes, jcache, debug_level >= 4, js_optimizer_extra_info, just_split=just_split, just_concat=just_concat)
      File "~/bin/emsdk_portable/emscripten/1.29.0/tools/shared.py", line 1637, in js_optimizer
        ret = js_optimizer.run(filename, passes, NODE_JS, jcache, debug, extra_info, just_split, just_concat)
      File "~/bin/emsdk_portable/emscripten/1.29.0/tools/js_optimizer.py", line 479, in run
        return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
      File "~/bin/emsdk_portable/emscripten/1.29.0/tools/tempfiles.py", line 39, in run_and_clean
        return func()
      File "~/bin/emsdk_portable/emscripten/1.29.0/tools/js_optimizer.py", line 479, in <lambda>
        return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, jcache, source_map, extra_info, just_split, just_concat))
      File "~/bin/emsdk_portable/emscripten/1.29.0/tools/js_optimizer.py", line 381, in run_on_js
        filenames = pool.map(run_on_chunk, commands, chunksize=1)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
        return self.map_async(func, iterable, chunksize).get()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 558, in get
        raise self._value
    AssertionError: Error in optimizer: Assertion failed: undefined

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:901:11)
        at Object.afterWrite (net.js:718:19)

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:901:11)
        at Object.afterWrite (net.js:718:19)

**Comment by aidanhs** [comment] 2015-04-03 13:56
Checking in latest incoming (1.30.4), still a problem. It also seems to give some extra info:
```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/tmp/tmpp7barF.jsfunc_4.js'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:286:15)
    at read (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:65:34)
    at Object.<anonymous> (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:7973:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by aidanhs** [comment] 2015-04-03 16:06
Hmm, I think the above is caused by the original error.
Slightly reduced command line: `emcc -s OUTLINING_LIMIT=100000 -s VERBOSE=1 -O2 -v ffmpeg.bc -o ffmpeg-all-codecs.js`.

**Comment by aidanhs** [comment] 2015-04-03 16:26
It's just after this (courtesy of EMCC_DEBUG):
```
DEBUG    root: applying js optimization passes: asm receiveJSON outline emitJSON
chunkification: num funcs: 18 actual num chunks: 16 chunk size range: 15693950 - 2537111
splitting up js optimization into 16 chunks, using 4 cores  (total: 173.39 MB)
```

Reduced test case:
```
$ wget -q http://aidanhs.com/tmpIoKYXj.jsfunc_4.js
$ node /home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js tmpIoKYXj.jsfunc_4.js noPrintMetadata asm receiveJSON outline emitJSON
Assertion failed: undefined
Stack: Error
    at assertTrue (eval at globalEval (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:111:8), <anonymous>:59:26)
    at /home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:2528:7
    at traverse (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:212:18)
    at traverseChildren (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:190:23)
    at traverse (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:217:9)
    at traverseChildren (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:190:23)
    at traverse (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:217:9)
    at traverseChildren (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:190:23)
    at traverse (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:217:9)
    at traverseChildren (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:190:23)
    at traverse (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:217:9)
    at getStackBumpNode (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:2524:3)
    at getStackBumpSize (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:2537:14)
    at analyzeFunction (/home/aidanhs/Desktop/js/emsdk/emscripten/incoming/tools/js-optimizer.js:5328:21)

undefined:60
    throw msg;
          ^
Assertion failed: undefined
```

**Comment by aidanhs** [comment] 2015-04-03 16:41
This assertion:
```
value[0] == 'binary' && value[1] == '|' && value[2][0] == 'binary' && value[2][1] == '+' && value[2][2][0] == 'name' && value[2][2][1] == 'STACKTOP' && value[2][3][0] == 'num'
```

Fails on this node:
```
[ 'binary',
  '&',
  [ 'binary', '+', [ 'name', 'STACKTOP' ], [ 'num', 31 ] ],
  [ 'unary-prefix', '-', [ 'num', 32 ] ] ]
```

**Comment by aidanhs** [comment] 2015-04-03 17:18
This line is being generated with `emcc -s VERBOSE=1 -O2 -g -v ffmpeg.bc -o ffmpeg-all-codecs.js`:
```
sp_a = STACKTOP = STACKTOP + 31 & -32;
```

**Comment by kripken** [comment] 2015-04-03 22:07
Thanks for the report and the investigation, basically we just need to ignore the special stack alignment sequence for very highly aligned stacks, which is rare. Fixed on incoming.

**Closed by kripken** 2015-04-03 22:07 UTC
