### ISSUE TITLE
Check EXPORTED_FUNCTIONS when deciding whether to link a static library

### ISSUE THREAD

**Issue by lptr** [kripken/emscripten#1017] opened 2013-03-31 12:38 UTC
`emcc` explicitly looks for only a `main` function when deciding whether to link a .a archive. So if your archive does not have a `main()` function (because it's a library), the .a archive won't be linked at all.

Setting `LINKABLE=1` does not help, and `EXPORTED_FUNCTIONS` are ignored as well.

A fix could be to add all exported functions to the list of `unresolved_symbols` here:
https://github.com/kripken/emscripten/blob/master/tools/shared.py#L733

A crude way to demonstrate how this fixes the problem is to write:

```
@staticmethod
def link(files, target):
  actual_files = []
  unresolved_symbols = set([fn[1:] for fn in Settings.EXPORTED_FUNCTIONS]) # tracking unresolveds is necessary for .a linking, s
```

This problem only arises when you are trying to link static libraries. With shared libraries `EXPORTED_FUNCTIONS` is properly taken into account already.

**Comment by mahmoudghonim** [comment] 2016-11-10 11:36
Dear Lorant,

I couldn't compile HarfBuzz JS.
https://github.com/prezi/harfbuzz-js/tree/master
OS: Linux 14.04 32-bit
installed tools: Python v2.7.6, nodejs v0.10.25, cmake v3.4.3, java v1.7.0_80
I modified build.gradle file
def emscriptenVersion = "master"      instead of      def emscriptenVersion = "1.22.0"

I faced ("installNpmPackages FAILED") when I was running ./gradlew assemble --stacktrace --debug command
I reached 100% for the built process and I faced "Build Failed ("installNpmPackages FAILED)"

Could you please help me 

09:59:40.867 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
09:59:40.869 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm'.
09:59:40.872 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
09:59:40.873 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm'' finished with exit value -1 (state: FAILED)
09:59:40.873 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':installNpmPackages'
09:59:40.874 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :installNpmPackages FAILED
09:59:40.875 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :installNpmPackages (Thread[main,5,main]) completed. Took 0.012 secs.
09:59:40.875 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 32.997 secs, idle: 0.013 secs
09:59:40.881 [ERROR] [org.gradle.BuildExceptionReporter] 
09:59:40.882 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:59:40.882 [ERROR] [org.gradle.BuildExceptionReporter] 
09:59:40.884 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:59:40.885 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':installNpmPackages'.
09:59:40.885 [ERROR] [org.gradle.BuildExceptionReporter] > A problem occurred starting process 'command '/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm''
09:59:40.886 [ERROR] [org.gradle.BuildExceptionReporter] 
09:59:40.886 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
09:59:40.887 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installNpmPackages'.
09:59:40.888 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
09:59:40.888 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
09:59:40.889 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
09:59:40.889 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
09:59:40.890 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
09:59:40.890 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
09:59:40.891 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
09:59:40.891 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
09:59:40.892 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
09:59:40.892 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
09:59:40.893 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
09:59:40.893 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
09:59:40.894 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
09:59:40.894 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
09:59:40.895 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
09:59:40.895 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
09:59:40.896 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
09:59:40.896 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
09:59:40.897 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
09:59:40.897 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
09:59:40.897 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
09:59:40.898 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
09:59:40.898 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
09:59:40.899 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
09:59:40.899 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
09:59:40.900 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
09:59:40.900 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
09:59:40.901 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
09:59:40.901 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
09:59:40.902 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
09:59:40.902 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
09:59:40.903 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
09:59:40.903 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
09:59:40.904 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
09:59:40.904 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
09:59:40.904 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
09:59:40.905 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
09:59:40.905 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
09:59:40.906 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
09:59:40.906 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
09:59:40.907 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
09:59:40.907 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
09:59:40.908 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
09:59:40.908 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
09:59:40.909 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
09:59:40.909 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
09:59:40.910 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
09:59:40.910 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
09:59:40.910 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm''
09:59:40.911 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:196)
09:59:40.911 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:325)
09:59:40.912 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:83)
09:59:40.912 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
09:59:40.913 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: net.rubygrapefruit.platform.NativeException: Could not start '/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm'
09:59:40.913 [ERROR] [org.gradle.BuildExceptionReporter] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
09:59:40.913 [ERROR] [org.gradle.BuildExceptionReporter] 	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
09:59:40.914 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:65)
09:59:40.914 [ERROR] [org.gradle.BuildExceptionReporter] 	... 1 more
09:59:40.915 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.IOException: Cannot run program "/home/mahmoud/Desktop/harfbuzz-js-master/emsdk/node/0.10.18_64bit/bin/npm" (in directory "/home/mahmoud/Desktop/harfbuzz-js-master"): error=2, No such file or directory
09:59:40.915 [ERROR] [org.gradle.BuildExceptionReporter] 	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
09:59:40.915 [ERROR] [org.gradle.BuildExceptionReporter] 	... 3 more
09:59:40.916 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.IOException: error=2, No such file or directory
09:59:40.916 [ERROR] [org.gradle.BuildExceptionReporter] 	... 4 more
09:59:40.916 [ERROR] [org.gradle.BuildExceptionReporter] 
09:59:40.917 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:59:40.917 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
09:59:40.918 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:59:40.918 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 36.212 secs

Thanks & Regards
Mahmoud Ghonim

**Comment by juj** [comment] 2016-11-13 19:06
I'm not sure if the above comment relates to this bug entry? I think bugs regarding harfbuzz-js should be reported at https://github.com/prezi/harfbuzz-js/issues. In any case, this issue is very old and there was no test case, so I'm closing it. If there is still trouble with the latest Emscripten, feel free to open a new bug to discuss!

**Closed by juj** 2016-11-13 19:06 UTC
