### ISSUE TITLE
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.

### ISSUE THREAD

**Issue by Fwjrei** [kripken/emscripten#4385] opened 2016-06-03 15:22 UTC
Result: Firefox (Developer Edition) on VMWare reports this error in the console for blacklisted video cards (for example, Firefox inside VMWare is on the blacklist). I asked GLFW for an un-antialiased buffer, why is Emscripten asking Firefox for an anti-aliased one? Firefox gives me the un-antialiased buffer I asked for, and my application works fine; I just want the error message in the console to go away.

Testcase:

```
#include <GLFW/glfw3.h>
int main()
{
    glfwInit();
    glfwWindowHint(GLFW_SAMPLES, 0); //seems to do nothing
    GLFWwindow* window = glfwCreateWindow(10, 10, "target window", NULL, NULL);
}
```

Compile with: emcc main.cpp -o a.html -s USE_GLFW=3
Tested with Emscripten 1.36 and 1.35.

**Comment by asRIA** [comment] 2016-06-03 16:16
Try to use `glut`. We confirmed that it works when you try to create a context without AA
https://github.com/kripken/emscripten/blob/master/src/library_glut.js#L516

**Comment by Fwjrei** [comment] 2016-06-03 16:53
Firefox gives you the right context, but emscripten still asks for the wrong one first. Are you working on a blacklisted video card? Normal video cards don't give the error.
Glut code, copied from https://people.mozilla.org/~vladimir/misc/paxdev2013-pres.pdf:
```
#include <GL/glut.h>
#include <stdio.h>

int main(int argc, char**argv)
{
	glutInit(&argc, argv);
	glutInitWindowSize(300, 300);
	glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB | GLUT_DEPTH);
	glutCreateWindow("Browser");

	glClearColor(0, 1, 0, 1);
	glClear(GL_COLOR_BUFFER_BIT);

	glutSwapBuffers();
}
```
Compile with emcc glut.cpp -o a.html
The glut code gives the same error as before.

**Comment by kripken** [comment] 2016-06-06 17:08
Is there an easy way to reproduce the problem (without a VM)?

Seeing the full stack trace might help understand what code is doing that.

**Comment by Kevin-Yin** [comment] 2016-06-09 14:32
Sure. Here's a file that will make Firefox believe you're on a blacklisted graphics card.

New file: spoofed-firefox.bat

Contents:```
SET MOZ_GFX_SPOOF_VENDOR_ID=0x80EE
"C:\Program Files\Mozilla Firefox\firefox.exe"
```
Change to "C:\Program Files (x86)\Mozilla Firefox\firefox.exe" if necessary.

**Comment by kripken** [comment] 2016-06-21 21:56
I can't reproduce the problem, using that env var on firefox nightly, and compiled with emscripten incoming, on the first testcase here.

If you still see it, might be worth using the stack trace to investigate where we ask webgl for the wrong aliasing option.

**Comment by juj** [comment] 2016-07-11 12:37
Posted https://bugzilla.mozilla.org/show_bug.cgi?id=1285937 discussing the blacklist item itself, I wonder  what caused the blacklisting, how long ago it was created, and if it is even accurate nowadays.

**Comment by juj** [comment] 2016-07-11 13:05
Debugging a bit, it looks like GLFW does use the GLFW_SAMPLES hint, see https://github.com/kripken/emscripten/blob/master/src/library_glfw.js#L755, and when GLFW_SAMPLES is set to 0 (or 1), that does correctly come out as false, but it is Firefox that is at fault, which unconditionally prints that error message even when antialiasing was not requested. Posted https://bugzilla.mozilla.org/show_bug.cgi?id=1285937#c1

**Comment by Stuk** [comment] 2018-09-27 18:38
I think this issue can be closed as the warning appears regardless of Emscripten when using WebGL on Mac Firefox. This is shown in the [linked bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1285937), and can be reproduced on https://get.webgl.org/

**Closed** 2018-09-27 18:40 UTC
Labels: GL
