### ISSUE TITLE
asm2wasm: Assertion `functionsMap.find(curr->name) == functionsMap.end()' failed

### ISSUE THREAD

**Issue by malbarbo** [kripken/emscripten#5288] opened 2017-06-09 16:49 UTC
I got [this](https://travis-ci.org/rust-lang/libc/jobs/241020070#L989) assertion error trying to build libc-test (an rust crate).

The error can be reproduced running `asm2wasm` on [this](https://github.com/kripken/emscripten/files/1064698/libc_test-fe212f5bb0be8707.asm.js.zip) file.

**Comment by kripken** [comment] 2017-06-09 18:17
Looks like that asm.js has a duplicate function,
````
function _memset($0,$1,$2) {
function _memset(ptr, value, num) {
````
Do you have the bitcode that it was generated from? The bug is probably at the bitcode => asm.js level.

**Comment by malbarbo** [comment] 2017-06-09 18:33
Here is it: [libc_test-fe212f5bb0be8707.0.o.zip](https://github.com/kripken/emscripten/files/1064919/libc_test-fe212f5bb0be8707.0.o.zip)

I'm using rust 1.18, which uses llvm 4.0...

**Comment by malbarbo** [comment] 2017-06-09 18:53
The same error happens with rust 1.17, that uses llvm 3.9.

**Comment by kripken** [comment] 2017-06-12 21:25
I'm not able to test this on emscripten incoming (1.37.13), as I get
````
$ emcc libc_test-fe212f5bb0be8707.0.o
llc: fastcomp/include/llvm/ADT/ilist_iterator.h:126: llvm::ilist_iterator<OptionsT, IsReverse, IsConst>::reference llvm::ilist_iterator<OptionsT, IsReverse, IsConst>::operator*() const [with OptionsT = llvm::ilist_detail::node_options<llvm::BasicBlock, true, false, void>; bool IsReverse = false; bool IsConst = false; llvm::ilist_iterator<OptionsT, IsReverse, IsConst>::reference = llvm::BasicBlock&]: Assertion `!NodePtr->isKnownSentinel()' failed.
````
Does that emcc command work for you? Or is there another way I should be reproducing the problem?

**Comment by malbarbo** [comment] 2017-06-12 22:45
Thanks for investigate this.

I can execute `emcc libc_test-fe212f5bb0be8707.0.o` with sdk-1.37.13-64bit, but there is missing symbol errors.

I think that the best way is to execute the rust compiler... If you do not want to install the rust compiler in your system, you can run it inside a docker container (if you install rustup outside a container, you can uninstall it with the command rustup uninstall, which removes everything that was installed):

```
git clone https://github.com/malbarbo/libc --branch emscripten
docker run -it -v $(pwd)/libc:/libc ubuntu:16.04
apt-get update && apt-get install curl build-essential
curl https://sh.rustup.rs -sSf | sh # choose option 1
. ~/.profile # set PATH
rustup target add wasm32-unknown-emscripten
# install emscripten
cd /libc
RUSTFLAGS="-Z print-link-args" cargo run --target wasm32-unknown-emscripten -p libc-test
```

The artifacts are generate in `target/wasm32-unknown-emscripten/debug/deps`. Setting RUSTFLAGS will print the arguments used to call emcc.

**Comment by kripken** [comment] 2017-06-13 02:40
If it doesn't crash for you with that version, then I suspect it's because the sdk build doesn't have assertions, while my local build does. I think we need to find out what's causing those asserts, as they could be the reason for the bug reported here (but it's also possible it's a red herring).

Perhaps is the bitcode old, or being linked with something old? A full rebuild from scratch of all bitcode files might help.

(I could try the rust compiler, but I don't know enough about it to easily debug into it. What I need here is just the emscripten commands it issues.)

**Comment by malbarbo** [comment] 2017-06-13 17:48
Using emscripten incoming I got the same error as you.

I create a [a zip file](https://github.com/kripken/emscripten/files/1072357/all.zip) with all required obj files to generate an .js. The command `emcc *.o *.rlib` works fine, but the command `emcc -s WASM=1 *.o *.rlib` fail with the original assertion error.

**Comment by malbarbo** [comment] 2017-06-13 19:27
To make it clear, using `emcc libc_test-fe212f5bb0be8707.0.o` gives the same assertion error you got, but given all object files as parameters works. Is this another issue?

**Comment by kripken** [comment] 2017-06-13 21:27
Thanks, now I can see the problem directly. #5299 should fix it.

(I don't see those assertions again, btw - that might be an entirely separate issue. Very strange.)

**Comment by rfk** [comment] 2017-06-14 10:36
FWIW I also hit this issue today in a different codebase, and can confirm that #5299 fixed it for me.

**Comment by kripken** [comment] 2017-06-17 01:16
Thanks for confirming @rfk. Should be fixed now with that PR merged.

**Closed by kripken** 2017-06-17 01:16 UTC

**Comment by malbarbo** [comment] 2017-06-19 19:14
Thanks @kripken!

**Comment by lilianmoraru** [comment] 2017-06-20 11:02
It would be nice to have this fix.
@kripken When do you think the next patch release might happen?

**Comment by kripken** [comment] 2017-06-20 18:15
I tagged git push `1.37.14` now.

**Comment by lilianmoraru** [comment] 2017-06-20 18:19
@kripken Thank you!!
