### ISSUE TITLE
Pointer_stringify() ignores length parameter when string contains values >= 128

### ISSUE THREAD

**Issue by ragfield** [kripken/emscripten#6578] opened 2018-05-24 02:52 UTC
Pointer_stringify() takes an optional length parameter, which it honors if all the characters are < 128.  If any characters are >= 128 the pointer is passed to UTF8ToString() without the corresponding length parameter.  If the string is not null-terminated UTF8ToString() will continue to read bytes past the specified length.

**Comment by curiousdannii** [comment] 2018-05-24 05:32
Sounds like a duplicate of #5936.

**Comment by ragfield** [comment] 2018-05-24 14:02
You are correct.

**Closed** 2018-05-24 14:02 UTC
