### ISSUE TITLE
PhantomJs error: 'no native wasm support detected

### ISSUE THREAD

**Issue by sara66** [kripken/emscripten#6602] opened 2018-05-30 18:15 UTC
My project which is using webassemly fails in unit test. the unit test is done using PhantomJS and it is displaying the following warning and error:

PhantomJS 2.1.1 (Windows 8.0.0) WARN: 'no native wasm support detected'
PhantomJS 2.1.1 (Windows 8.0.0) LOG: 'no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods'

Do you have any suggestions?

Thank you,
Sara

**Comment by kripken** [comment] 2018-05-30 23:57
Looks like a duplicate of https://github.com/WebAssembly/binaryen/issues/1574

**Closed by kripken** 2018-05-30 23:57 UTC
