### ISSUE TITLE
Emscripten 1.35.10 with CMake fails to generate system libs, when static libs are .bc

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3939] opened 2015-11-26 16:58 UTC
When building an Emscripten tag 1.35.10 app with CMake, with this small change to the toolchain file so that it produce bitcode (.bc) static libs instead of archives (.a)

```cmake
set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LIBRARY_SUFFIX ".bc" CACHE STRING "" FORCE)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".bc" CACHE STRING "" FORCE)
set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_C_COMPILER> -o <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "" FORCE)
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_CXX_COMPILER> -o <TARGET> <LINK_FLAGS> <OBJECTS>" CACHE STRING "" FORCE)
```

...Emscripten gets into an infinite loop when trying to generate system libs...

```
WARNING:root:generating system library: libcxx_noexcept.a...
```

...with the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\emsdk-1.35.0-portable-64bit\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\emsdk-1.35.0-portable-64bit\python\2.7.5.3_64bit\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named em++
```

Small test case to reproduce it : [download here](https://autodesk.box.com/s/ww57p42rwj4wno7z46ewm81mwocr2vg5)

This worked fine in 1.35.4 and lower. I don't know which version it stopped working but we know that in 1.35.10 its broken.

**Comment by gouletr** [comment] 2015-11-26 17:01
The test case includes a batch file (make.bat) if you don't know how to invoke cmake. You can rewrite it in python or any other shell script language that you like, and integrate it in your tests.

**Comment by kripken** [comment] 2015-11-26 18:23
I tried to reproduce on linux with `emconfigure  cmake .` and `make`, and don't see the problem. So it might be windows-specific. @juj, could you try this please?

@gouletr: Another thing that could help is to bisect and see which specific commit starts to fail for you.

**Comment by gouletr** [comment] 2015-11-26 19:38
We are not using `emconfigure` or any of those scripts. We use pure CMake, exactly written as in the `make.bat` file. Could be Windows specific.

**Comment by kripken** [comment] 2015-11-26 19:43
I see. I don't know much about cmake or windows .bat files, but if there is a way to get something equilvalent for that .bat file for linux, I could test that.

**Comment by gouletr** [comment] 2015-11-26 20:48
Well I don't have a linux machine, but technically speaking if you open the file make.bat, you'll see its pretty straightforward. You could manually type these commands in a shell:
```
mkdir build
cd build
cmake -G "Makefiles" -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake ..
cmake --build .
```

**Comment by kripken** [comment] 2015-11-26 20:58
Ok, I tried

````
cmake -DCMAKE_TOOLCHAIN_FILE=/home/alon/Dev/emscripten/cmake/Modules/Platform/Emscripten.cmake
cmake --build .
````

and it works ok.

When I tried to do it in a subdir, then the first command even with `..` seems to emit the stuff in the parent dir, so `cmake --build .` fails but with `..` succeeds, but then it builds in the parent dir anyhow.

So either I am doing the subdir aspect wrong, or this is a windows-specific issue.

**Comment by gouletr** [comment] 2015-11-26 21:00
cmake is made to build out of source, that's why you should do it in a subfolder, like the build folder I mentioned. If that works then it must be a Windows issue.

**Comment by kripken** [comment] 2015-11-26 21:05
Do the test suite cmake tests pass for you? `tests/runner.py test_zlib`, `test_openjpeg` and `test_the_bullet` all use cmake. Also `other.test_cmake`.

**Comment by gouletr** [comment] 2015-11-26 21:22
test_zlib result:
```
======================================================================
ERROR: test_zlib (test_core.default)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\emsdk-1.35.0-portable-64bit\emscripten\tag-1.35.10\tests\test_core.py", line 6064, in test_zlib
    libraries=self.get_library('zlib', os.path.join('libz.a'), make_args=make_args, configure=configure),
  File "D:\emsdk-1.35.0-portable-64bit\emscripten\tag-1.35.10\tests\runner.py", line 460, in get_library
    copy_project=True, env_init=env_init, native=native)
  File "D:\emsdk-1.35.0-portable-64bit\emscripten\tag-1.35.10\tools\shared.py", line 1274, in build_library
    raise Exception('could not build library ' + name + ' due to exception ' + str(e))
Exception: could not build library zlib due to exception [Errno 2] No such file or directory: 'D:/emsdk-1.35.0-portable-64bit/tmp\\emscripten_test_def
ault_ozflwo\\building\\zlib\\libz.a'

----------------------------------------------------------------------
Ran 1 test in 3.938s
```

**Comment by gouletr** [comment] 2015-11-26 21:30
I forgot to mention it happens when I run the activation (before it clears the cache). If somehow I already had the cached files, everything is fine.

**Comment by gouletr** [comment] 2015-11-26 21:42
other.cmake_test succeeded. So I don't know what is going on... how do I add more debug info to this?

**Comment by kripken** [comment] 2015-11-26 21:45
I would try to see what is different between your usage, and that test. One guess is that it uses `emconfigure` which sets env vars so that cmake can find emscripten. Perhaps removing that from the test, and making it more like your usage, would break the test, and pinpoint the issue.

**Comment by gouletr** [comment] 2015-11-27 16:50
Just tested `1.35.8`, and it works fine. I'm going to test `1.35.9`...

**Comment by gouletr** [comment] 2015-11-27 17:02
`1.35.9` is ok too. So its a commit between `1.35.9` and `1.35.10`.

**Comment by kripken** [comment] 2015-11-27 18:52
In that case it definitely sounds related to the emcc/em++ changes (7b018761e9f1d6090afe4d86373caff6336638b3, 62e55bea938e682d420fbea992e302837d08b689 and bcc5d85ea96b71f55690f14112a63f771c2a2514). Knowing which specifically might help.

Does the problem go away if you use `emconfigure` to invoke cmake and `emmake` to invoke the make step? That's how it's tested in the test suite I believe, perhaps that is the relevant difference?

**Comment by gouletr** [comment] 2015-11-27 19:09
Ok I did a local test and looks like commit bcc5d85ea96b71f55690f14112a63f771c2a2514 is the faulty one. I changed this in file `em++`:
```
if sys.version_info.major == 2:
  import emcc
  emcc.run()
else:
  import os, subprocess
  sys.exit(subprocess.call(['python2', os.path.join(os.path.dirname(__file__), 'emcc.py')] + sys.argv[1:]))
```
to this:
```
import os, subprocess
sys.exit(subprocess.call(['python', os.path.join(os.path.dirname(__file__), 'emcc.py')] + sys.argv[1:]))
```
...and now it works. Not sure why import emcc would fail in my case, but it does. Also, switching back to doing the subprocess call didn't work with `python2`, I had to put back `python`.

**Comment by kripken** [comment] 2015-11-27 19:18
If it's hitting the import, then your default system python is 3? If so that might be why we don't see this issue on the bots. If not then perhaps we are not detecting the python version properly?

**Comment by gouletr** [comment] 2015-11-27 19:23
When I open a new console window, `python --version` returns `2.7.8`. But after I call `emsdk activate`, it returns `2.7.5`. In your code, you do `if sys.version_info.major == 2:` so we always end up in that case. What I did to fix it is to remove that case and always execute the else part.

**Comment by gouletr** [comment] 2015-11-27 19:27
Sorry maybe I wasn't clear. I entirely removed the if else block of the code above and only kept the bottom part, which is almost what it was doing before change bcc5d85. I don't have Python 3.

**Comment by kripken** [comment] 2015-11-27 19:28
Oh, I see, then `import emcc ; emcc.run()` is what fails?

Or rather, doesn't fail immediately, but leads later to the failure mentioned in the first comment?

This does look like a windows-specific problem with imports working differently than other platforms.

**Comment by gouletr** [comment] 2015-11-27 19:29
Yes exactly. `import emcc ; emcc.run()` that fails.

**Comment by gouletr** [comment] 2015-11-27 19:31
But it doesn't fail for my project's code. It only fails for Emscripten system libs, when the cache was cleared or outdated. That's super strange, but I'm not a python expert so I can't comment on this.

**Comment by kripken** [comment] 2015-11-27 19:34
Me either, no idea what's going on. I suspect it has to do with cmake invoking emcc in a way that makes the import not work - different path? different env vars? If the latter, then using `emconfigure/emmake` as suggested earlier, which we recommend doing anyhow, might help.

**Comment by gouletr** [comment] 2015-11-27 19:43
It would be somewhat difficult to do that with our build script - it would be a huge exception. Right now we build all platforms (Win32/Win64/iOS/Android/PS4/XB1/WebGL) with CMake invocations, and we'd like to keep it clean.

Besides, using `emconfigure/emmake` shouldn't be forced; we should be able to use Emscripten CMake toolchain file just like all other CMake toolchain files out there, which doesn't require special scripts like those.

Can we just revert it to invoke the subprocess rather than doing the import emcc? That's what you did before and it used to work just fine.

**Comment by kripken** [comment] 2015-11-27 19:49
We can't easily revert it, because it fixed a problem with systems with python3 as default, which is becoming more common.

However, those python3 systems are mainly linux, and not windows. Perhaps we could add another if, `if windows then subprocess run python (and not python2)`, assuming you can confirm that works, and if @juj is ok with it.

**Comment by gouletr** [comment] 2015-11-27 19:51
Or we can dig further to find why the import fails later on, but I will need help since I don't know where to start.

**Comment by gouletr** [comment] 2015-11-27 19:52
But if we can do the change you suggest for windows systems only, it would allow me to test the changes you did for NaN and SSE2 function table.

**Comment by kripken** [comment] 2015-11-30 22:18
I wouldn't want to make a windows-specific change without @juj, and he went on vacation this week I'm afraid. Perhaps apply the change locally for your builds, for now?

**Comment by gouletr** [comment] 2015-11-30 22:41
Yes sure no problem. We're not in a rush to upgrade.

**Comment by mhenschel** [comment] 2015-12-04 16:37
I ran into the same issue on windows in the incoming branch.

**Comment by juj** [comment] 2015-12-18 11:06
Putting this on my short list to investigate..

**Comment by juj** [comment] 2015-12-19 21:27
This should be fixed when the above pull request lands.

**Comment by kripken** [comment] 2015-12-21 19:34
It landed, closing.

**Closed by kripken** 2015-12-21 19:34 UTC
Labels: windows

**Comment by gouletr** [comment] 2016-01-04 15:10
Thanks guys! I will try this out asap.

**Comment by gouletr** [comment] 2016-01-05 22:24
Confirmed this now works properly. thanks!
