### ISSUE TITLE
can't build on windows 10

### ISSUE THREAD

**Issue by frankinshtein** [kripken/emscripten#3877] opened 2015-10-25 09:52 UTC
I reinstalled system from Windows 8.1 to Windows 10 and installed latest emsc.

emscripten not working anymore, error:

d:/emscripten/emscripten/1.34.1/em++.bat: line 1: @echo: command not found
c:\Python27\python.exe: can't open file '%~dp0\em++': [Errno 2] No such file or directory

Looks like in the em++.bat global variables and commands (@echo) doesn't exist

**Comment by frankinshtein** [comment] 2015-10-31 09:21
Issue was created for bug related with portable emsdk arcieve.

I reinstalled emscripten using offline installer and it works fine..

**Comment by kripken** [comment] 2015-10-31 23:00
@juj, have you tested on a windows 10 machine?

**Comment by asRIA** [comment] 2015-11-01 14:09
I've tested on 2 windows machines with Emscripten 1.34.1, 1.34.11 and Incoming about 1 week ago and it worked.

**Comment by frankinshtein** [comment] 2015-11-01 14:12
btw,
I'm using CMake + make

see example:
https://bitbucket.org/oxygine/oxygine-framework/src/9ac72d76aab8acc05831e02da9266f9ad686d9be/examples/HelloWorld/proj.emscripten/?at=default

**Comment by juj** [comment] 2015-11-02 19:20
I tested the latest on Windows 10 now, and could not reproduce an issue there. Sounds like you got it working via the offline installer(?). We'll have an updated emsdk package out soon, when that is bundled, I'll double-check the online installer there to close this.

**Comment by juj** [comment] 2015-11-13 22:56
New emsdk with Emscripten 1.35.0 went live today: https://groups.google.com/d/msg/emscripten-discuss/TW-AvHt-lc4/_59T4YBxBQAJ . Does issues still persist there? If so, can you post full logs and the commands?

**Comment by asRIA** [comment] 2015-11-23 21:15
We run this problem on 2 machines at this moment as far as I remember one of this machine was Windows 8.1
- project runs on Emscripten 1.35.0 from binary
- project is CMake based, with generator set as `Unix Makefile`
- We use `Emscripten.cmake` as a toolchain
- Project works on most machines but 2 specific ones. 
- Tested with cmake 3.4-rc3

Steps to solve project: 
- We suspected that some system tool overrides console, but it looks like cmd is a default one. 
- We suspected that http://strawberryperl.com/ made some complications but it is still broken when this tool has been moved, and it work on other machine with newly installed strawberry
- Diff between project generated on machine where it work and where it is broken has no obvious difference.

Soon we will try to provide some tracks after compilation with ```EMCC_DEBUG=1``` and with ```EM_BUILD_VERBOSE=1```

At this moment looks that emcc could invoke build incorrectly.

**Comment by juj** [comment] 2015-11-24 12:22
The generator `Unix Makefiles` is not good on Windows, unless one installs Cygwin or MSYS or some other POSIX environment emulator on Windows. It might be that the problem is related to that, in which case it is not likely specific to Windows 10 or emsdk at all.

When building CMake projects with Emscripten on Windows, I recommend installing the MinGW toolchain and using the `-G MinGW Makefiles` generator, or installing Visual Studio, and using `-G NMake Makefiles` (though that's a bit less tested). These both are native build systems on Windows, as opposed to `Unix Makefiles`, which needs to be emulated.

With `MinGW Makefiles` generator, one builds with `mingw32-make` instead of `make`, and with `NMake Makefiles`, one builds with `nmake` instead of `make`.

**Comment by asRIA** [comment] 2015-11-24 12:28
Hi, 
I was to quick with investigation and I did some extra mile in this. 
Problem was related with having portable version 1.34.1 and then it was updated to 1.35.0
After downloading either portable 1.35.0 or offline installer it started to work on both machines. 

Thank you for your attention.

**Comment by juj** [comment] 2015-11-24 15:38
Thanks, let me close this as resolved. If there are still issues with the latest versions, let's open new issues to track them specifically.

**Closed by juj** 2015-11-24 15:38 UTC
Labels: emsdk, windows
