### ISSUE TITLE
Consider handling Unicode problem in Python script emsdk

### ISSUE THREAD

**Issue by kovzol** [kripken/emscripten#3036] opened 2014-12-04 10:32 UTC
On my Ubuntu 14.04 I get the following error:

$ ./emsdk install latest
Installing 'sdk-master-64bit'..
Installing 'clang-master-64bit'..
Traceback (most recent call last):
  File "./emsdk", line 1319, in <module>
    sys.exit(main())
  File "./emsdk", line 1304, in main
    tool.install()
  File "./emsdk", line 804, in install
    success = tool.install()
  File "./emsdk", line 812, in install
    success = build_fastcomp_tool(self)
  File "./emsdk", line 415, in build_fastcomp_tool
    fastcomp_root = tool.installation_path()
  File "./emsdk", line 637, in installation_path
    return sdk_path(pth)
  File "./emsdk", line 109, in sdk_path
    return to_unix_path(os.path.join(os.path.dirname(os.path.realpath(__file__)), path))
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

This helped me to work around the problem: http://stackoverflow.com/a/21470447 --- that is, I added two lines after the "import ..." statement.

Maybe you want to do the same change in the script. Thanks, Zoltan

**Comment by juj** [comment] 2015-03-18 12:28
This looks like it was duplicate of #3147, and it was fixed in https://github.com/juj/emsdk/commit/81aaba9b4e34010564551649bc2e44c8321463b7 .

**Closed by juj** 2015-03-18 12:28 UTC
Labels: emsdk
