### ISSUE TITLE
Upstream Clang/LLVM produces unsupported relocations

### ISSUE THREAD

**Issue by ddcc** [kripken/emscripten#4422] opened 2016-06-30 22:26 UTC
Upstream Clang/LLVM (within the past week or so) produces relocations that don't seem to be supported by `s2wasm` when compiling C++ programs.

On the following vtable, I get the message `Fatal: Unknown relocation: $_ZTV1B
`

```
.L__unnamed_1:
	.int32	0
	.int32	_ZTI1B
	.int32	_ZN1B1fEv@FUNCTION
	.skip	4
	.int32	0
	.int32	_ZTI1C
	.int32	_ZN1C1fEv@FUNCTION
	.size	.L__unnamed_1, 28

	.type	.L__unnamed_2,@object
	.section	.rodata,"a",@progbits
.L__unnamed_2:
	.size	.L__unnamed_2, 0


_ZTV1B = .L__unnamed_1
	.size	_ZTV1B, 12
_ZTV1C = .L__unnamed_1+16
	.size	_ZTV1C, 12
```

vtable.cpp: https://gist.github.com/ddcc/ff531972825cc6bbf8e9f8365fb6891c
vtable.s: https://gist.github.com/ddcc/8192d691d4d31c27dd3e3c23aff897c2

**Comment by kripken** [comment] 2016-06-30 22:32
Is this on current binaryen master?

Does this only show up on such a very recent LLVM+clang, i.e., is this a regression in the wasm backend? cc @sunfishcode

**Comment by sunfishcode** [comment] 2016-06-30 22:37
The wasm backend hasn't changed recently; it's possible this is a change in target-independent parts of LLVM. Does s2wasm support the "sym = value" syntax?

**Comment by ddcc** [comment] 2016-06-30 22:51
Sorry, it turns out I have some local transforms on the IR that are triggering this bug. Yes, this is on binaryen master. The `sym = value+offset` syntax doesn't seem to be supported by `s2wasm`.

Here is the IR that produces the above unsupported output:
```
@0 = private constant { [3 x i8*], [4 x i8], [3 x i8*] } { [3 x i8*] [i8* null, i8* bitcast ({ i8*, i8*, i8* }* @_ZTI1B to i8*), i8* bitcast (i32 (%class.B*)* @_ZN1B1fEv to i8*)], [4 x i8] zeroinitializer, [3 x i8*] [i8* null, i8* bitcast ({ i8*, i8*, i8* }* @_ZTI1C to i8*), i8* bitcast (i32 (%class.C*)* @_ZN1C1fEv to i8*)] }
@_ZTV1B = internal alias [3 x i8*], getelementptr inbounds ({ [3 x i8*], [4 x i8], [3 x i8*] }, { [3 x i8*], [4 x i8], [3 x i8*] }* @0, i32 0, i32 0)
```

In comparison, this IR is fine:
```
@_ZTV1B = internal unnamed_addr constant [3 x i8*] [i8* null, i8* bitcast ({ i8*, i8*, i8* }* @_ZTI1B to i8*), i8* bitcast (i32 (%class.B*)* @_ZN1B1fEv to i8*)], align 4
```

**Comment by kripken** [comment] 2016-06-30 22:55
@ddcc: Ok, if it's not emitted by clang directly then it's low priority to fix, which is good to know.

@sunfishcode: Looks like s2wasm doesn't support that. The main process() loop looks for stuff starting in `.` (like `.type` etc.), and stops when it sees `_ZTV1B = .L__unnamed_1`. So I guess we should implement that - what is it, though? alias, copy, or something else?

**Comment by sunfishcode** [comment] 2016-07-01 00:20
It's an alias. It's assigning the symbol "_ZTV1B" to hold the value of the symbol ".L__unnamed_1".

**Comment by ddcc** [comment] 2016-07-01 02:31
Apparently I also opened this against the wrong repository. Here's the draft pull request implementing this: https://github.com/WebAssembly/binaryen/pull/615 .

**Comment by kripken** [comment] 2016-07-01 15:49
Oh right, this is the emscripten repo. Let's close this then and focus on the PR.

**Closed by kripken** 2016-07-01 15:49 UTC
