### ISSUE TITLE
emrun firefox behavior is pretty rude

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3391] opened 2015-04-22 21:53 UTC
The default behavior for running emrun against Firefox is pretty good at destroying existing sessions, blowing all of a user's tabs away - the way emrun kills the process makes FF think a session crashed, and the next time you use emrun, the session restore tab will appear, then get blown away when emrun terminates the browser - and now the user's tabs are all gone forever. Maybe this is a firefox bug, but it feels like an emrun bug because emrun could do something else :-)

My recommendation is for emrun to always launch a new instance and do so using a dedicated profile, like this:

```python
  if 'firefox' in " ".join(browser).lower():
    browser_args += ['-P', 'emrun', '--no-remote']
```

The above ensures a new firefox instance is already created and that it doesn't communicate remotely (i.e. calling firefox afterwards won't open a new tab in our instance). Only downside is that if the 'emrun' profile doesn't exist, it won't silently create a new one. You can do that with ```firefox --CreateProfile emrun``` but that needs to be a separate invocation.

RIP my tabs :sob:

**Comment by juj** [comment] 2015-04-23 07:27
Emrun should not terminate the browser process as default behavior. Did you see it do so? Termination is done only if explicitly passing `--kill_start` or `--kill_exit` commands which will provide what they advertise.

**Comment by kg** [comment] 2015-04-23 15:21
Right, I'm referring to how those features work. I was confused as to what kill_start and kill_exit actually do. I was using firefox_nightly as the browser and kill_start nuked my Firefox Developer Edition, and then it launched nightly using my main profile, which hosed my session.

With the suggested arguments and just kill_exit, it'll launch a new session of nightly with just the emscripten app in it, then kill just that one at the end.

**Comment by juj** [comment] 2015-04-23 15:45
Ok. Let me close this, as they are not default behavior, and they work exactly as intended to do. Adding an option to run with a custom profile is something to consider, but I don't want to make that the default, since it comes with additional configuration complexity as you also mention. At that point it's probably easier to migrate to using mozrunner instead.

**Closed by juj** 2015-04-23 15:45 UTC
