### ISSUE TITLE
browser.test_sdl_canvas_alpha looks wrong on Firefox Nightly

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4069] opened 2016-01-30 00:09 UTC
The test fails on nightly but passes on release. Chrome looks like release. Perhaps nightly regressed? But the output looks "ok", I wonder if this isn't just a change like enabling aliasing, do you know @juj?

**Comment by juj** [comment] 2016-02-01 13:20
On my OS X laptop, the test passes in both stable and Nightly. Screenshots of the two cases in the test in both look like this:

<img width="1148" alt="screen shot 2016-02-01 at 3 14 38 pm" src="https://cloud.githubusercontent.com/assets/225351/12718337/b5023576-c8f6-11e5-8409-73b44bb580a2.png">

<img width="1154" alt="screen shot 2016-02-01 at 3 14 46 pm" src="https://cloud.githubusercontent.com/assets/225351/12718341/bf1902ba-c8f6-11e5-9bc7-0da247ece90f.png">

On Windows bot we have skipped that test for a long time (http://clb.demon.fi:8112/builders/win-incoming/builds/1163/steps/Tests-browser-firefox-stable/logs/stdio), but I've failed to print in the log why we do that (a bit sloppy on my part :( ). I presume it had been due to rasterization related differences.

On Linux bot, the test passes (http://clb.demon.fi:8112/builders/ubuntu-incoming/builds/1304/steps/browser%20suite%20-%20firefox%20stable/logs/stdio), though only stable release Firefox is currently being tested.

Can you capture a screenshot of what it looks like for you?

**Comment by kripken** [comment] 2016-02-02 23:15
Hmm, this is what I see:

![bug2](https://cloud.githubusercontent.com/assets/173661/12767737/d1890bf6-c9bf-11e5-87c1-d589b9269862.png)

**Comment by kripken** [comment] 2016-02-02 23:16
It looks different. Weird. Any idea?

**Comment by asRIA** [comment] 2016-02-03 09:02
I have the same result in Nightly (`47.0a1 (2016-02-01)`) on Windows.

**Comment by juj** [comment] 2016-02-03 12:23
Oh! @kripken's screenshot suggests an old issue is raising its head. The text is additively blended, and there are so many overlapping text items that the color converges toward yellow, rgb=(255,255,0). There are quite not enough text elements to make the blend full yellow, so it goes around to orange, rgb ~= (255,192,0), i.e. the green channel does not yet saturate, but red does. The issue seems to be that instead of clamping the additive blend of red(255)+red(255)=red(255), it seems to wrap around and produce red(255)+red(255)=0, and for the orangeish color (255,192,0) it incorrectly turns to (0,192,0) which is the greenish shade there.

See this old commit: https://github.com/kripken/emscripten/commit/797656ac43f6d998e5d6ccd4bd1c58b55f9527e0

Historically the reference image was captured with the blend wraparound bug included in it.

@kripken: you mention that stable works and Nightly doesn't? Would you be able to use `mozregression` to bisect when Firefox regressed?

@asRIA : does Firefox Stable work ok for you?

**Comment by asRIA** [comment] 2016-02-04 06:48
@juj Indeed the same problem happen on stable version / 41.0.2

**Comment by kripken** [comment] 2016-02-08 21:57
@juj: I can't seem to run mozregression, it keeps saying it can't launch the app. There doesn't seem to be a log or anything I can see to find out more? Are you familiar with the tool, or should I file an issue for them?

**Comment by juj** [comment] 2016-02-08 23:22
I am familiar with using it, but have not seen this kind of error before. To install I just use `pip install mozregression`, which has worked ok for me. What is the exact error message? We do have a bugzilla category for mozregression bugs, might file it there if can't figure it out.

**Comment by kripken** [comment] 2016-02-08 23:57
Oh thanks, looks like just the gui version is broken. The `pip` shell one is fine.

**Comment by kripken** [comment] 2016-02-08 23:58
Ok, bisection found

https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=f36a4a4ff73f1184f569fd9152b98fe8d8d3866a&tochange=cea2883034cbb4485c1ee0047cd6a7cfe4b9b652

A bunch of stuff looks relevant. Does anything look particularly suspicious to you?

**Comment by kripken** [comment] 2016-02-09 00:13
There is a cairo rendering change for linux - that sounds relevant. Will comment there.

**Comment by asRIA** [comment] 2016-02-10 06:42
Sorry for making confusion, I used a wrong reference and I though that result on my PC is wrong, but it is correct actually.

**Comment by juj** [comment] 2016-10-17 15:18
Saw this just occur on the linux buildbot, which has Ubuntu 16.04 and Intel HD 3000 GPU and Firefox 47. Updating to Firefox 49 fixes it, like was discussed in the bug about cairo that @kripken linked to above. Closing as resolved.

**Closed by juj** 2016-10-17 15:18 UTC
Labels: tests
