### ISSUE TITLE
<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>

### ISSUE THREAD

**Issue by novellizator** [kripken/emscripten#6548] opened 2018-05-17 11:58 UTC
https://stackoverflow.com/questions/50348772/urlopen-error-ssl-tlsv1-alert-protocol-version-tlsv1-alert-protocol-version

**Comment by willemneal** [comment] 2018-05-17 14:56
I ran into the same problem.  I tried updating openssl on MacOS and using a newer version of python, but it still didn't work.

A hacky work around that worked for me is to download the failing file manually into the zips folder.

For example:
```
cd zips
wget https://github.com/kripken/emscripten/archive/1.38.0.tar.gz
```

Then try to install again and it should work.

**Comment by kripken** [comment] 2018-06-20 15:47
I think this is a duplicate of #6275

**Closed by kripken** 2018-06-20 15:47 UTC
