### ISSUE TITLE
Force Embind on higher Optimisation levels

### ISSUE THREAD

**Issue by zapfdk** [kripken/emscripten#3521] opened 2015-06-08 13:30 UTC
Hi,
I am exporting classes and functions with Embind. But if am building the project with higher optimisation levels (-O2 and higher), I receive 
`TypeError: functionName is not a function`
Is there a way to force the compiler and linker to keep the EMSCRIPTEN_BINDINGS?
I tried to force the Closure Compiler not to run, but still I can't use the functions anymore.

**Comment by kripken** [comment] 2015-06-08 17:46
Sounds like a bug, do you have a testcase showing the issue?

**Comment by zapfdk** [comment] 2015-06-09 10:49
I set up a project, with similar functions and class that produces the same error.
You can find it in my repository:
https://github.com/zapfdk/EmbindTest

**Comment by AlexPerrot** [comment] 2015-06-09 17:18
Hi,
I looked at the project you in your repository and the `setParameters()` and `RandomClass`are available in both Debug and Release js you supplied...

**Comment by zapfdk** [comment] 2015-06-10 07:38
Ok, this is really strange.
The Debug Build works fine, the Release Build still gives me the:
TypeError: Module.setParameters is not a function
Error.
But I don't see, how the function and the class are available for you? 
When searching in the particular .js file, I can find setParameters and RandomClass in the Debug .js file, but not in the Release version.

**Comment by AlexPerrot** [comment] 2015-06-10 14:16
I can confirm that the names `setParameters` and `RandomClass` only appear in the debug version, but they are the symbols for the c++ functions, not the name of the bindings. In the Release version, these symbols have been minified and do not appear anymore.
To check if the functions are available, I simply used the js console in firefox. What did you use ?

**Comment by zapfdk** [comment] 2015-06-10 14:23
I used the Test.html that you can find in the particular build folder. It is exactly the same .html code. In the debug build it is working as expected, it should simply print "Success!" to the screen, when the functions and classes are found. The debug version does this. The release build obviously doesn't and prints the error message, that I wrote above, to the console

**Comment by AlexPerrot** [comment] 2015-06-10 14:53
Ok, the problem comes from the initialization process of emscripten compiled code, not embind itself.
I have a similar problem discussed here : https://groups.google.com/forum/#!topic/emscripten-discuss/kgJFTKXRe-0

In fact, you can't always call embind code right after including the compiled js, because the initialzation of the EMSCRIPTEN_BINDINGS happens asynchronously.
Look at the files in the your Release and Debug directories : there is `.mem` file in Release which is not there in Debug. This is the memory initialization file. It needs to be download by the compiled js before running the EMSCRIPTEN_BINDINGS initializers.

You can use several methods to get your code executed after initialization : 
- The `postRun` callback
- The `main` function
- I also have used `window.onload` with success
And there are probably more...

**Comment by zapfdk** [comment] 2015-06-10 15:07
You are right!
window.onload() works perfectly fine for me. Thank you very much!

**Comment by froydnj** [comment] 2018-03-30 20:06
@kripken, it seems like there is no issue here, can we close this and #3546 as well?

**Comment by kripken** [comment] 2018-04-02 18:14
Thanks, yeah, closing.

Btw, can only maintainers close issues they didn't open? I thought anyone could. I don't see an option to change that either way.

**Closed by kripken** 2018-04-02 18:14 UTC
Labels: embind

**Comment by froydnj** [comment] 2018-04-02 18:23
> Btw, can only maintainers close issues they didn't open? I thought anyone could. I don't see an option to change that either way.

I do not have a button to close issues I didn't open.  Nor do I have a button to reopen this issue.  Sorry for having to route everything through you. :(

**Comment by kripken** [comment] 2018-04-02 19:48
No problem. I'm surprised github doesn't let people close issues, though. I see it's the same on other repos too, I guess that's just how it works...
