### ISSUE TITLE
Header file not found error in Visual Studio 2010

### ISSUE THREAD

**Issue by ZengruiWang** [kripken/emscripten#3516] opened 2015-06-04 18:16 UTC
Hi,
I am trying to port a very big project using Emscripten with Visual Studio 2010. Sometimes I ran into some errors like: "xxx.h" file not found, even though the xxx.cpp and xxx.h is in the same directory. The weird thing is when I compiled it again, it just successfully built. It seems like the compilation is not very stable. Any idea how to improve it?

Thank you!

**Comment by juj** [comment] 2015-06-04 18:36
Sorry, there is not much room to react to in this kind of bug report that vaguely states an instability without offering steps to reproduce. Please try to offer a way reproduce the issue (if it doesn't occur always, then steps that at least occur x% of the time, but systematically, can be enough). Also, let me close this here, since bugs to Visual Studio integration should go to https://github.com/juj/vs-tool

**Closed by juj** 2015-06-04 18:36 UTC
