### ISSUE TITLE
import object field 'global.Math' is not an Object

### ISSUE THREAD

**Issue by mdboom** [kripken/emscripten#6365] opened 2018-03-22 19:39 UTC
When using some entries in math.h that have Javascript equivalents from a SIDE module, the following exception is raised on loading that SIDE module:

```
Error in loading dynamic library: TypeError: import object field 'global.Math' is not an Object
```

I've put a standalone example up here: https://github.com/mdboom/emscripten-side-module-issue

Adding `-lm` to link command doesn't seem to change behavior.

**Comment by kripken** [comment] 2018-03-22 20:20
Thanks for the report and the testcase!

Side note, the script there has a typo,
```
-o EXPORTED_FUNCTIONS='["_main", "global.Math"]'
```
Should be `-s`, so the exported functions were not noticed. However, this is ironic, it only seems related. The real issue is that functionality like Math should not need to be exported or imported manually, it should work automatically, and we had a bug in handling that (and no test). Fix in #6366

**Comment by mdboom** [comment] 2018-03-23 15:36
Thanks.  #6366 indeed resolves this issue for me.

**Comment by kripken** [comment] 2018-03-23 16:39
Great, thanks. Merged that PR.

**Closed by kripken** 2018-03-23 16:39 UTC

**Comment by skandonkumar** [comment] 2019-12-16 22:17
I have a similar issue.
TypeError: WebAssembly Instantiation: Import #0 module="global.Math" error: module is not an object or function

An outline of what I'm trying to do -
Converted a C library to WASM using EMScripten and wrote wrapper code to develop SDK. Used WebPack to bundle the whole thing by using "wasm-loader" which converts the WASM file into 8 bit integer array. The output is a single JS file but when we try to make API calls through this JS to the C library, I get the above mentioned error. It would be of great help if anyone could help me with some solutions. Thank You

**Comment by kripken** [comment] 2019-12-17 22:18
@skandonkumar it's probably simplest to just use the latest emscripten, with the upstream backend. It will not use `global.Math` from JS.

**Comment by skandonkumar** [comment] 2019-12-18 16:02
@kripken Thank You so much. I updated my emsdk and the `global.Math` error was resolved. However, I encountered another error saying --
**LinkError: WebAssembly Instantiation: Import #0 module="env" function="sbrk" error: function import requires a callable**

Am I supposed to add the function "sbrk" in the env in the Emscripten generated JS file before using WebPack?
Any help would be greatly appreciated :)

**Comment by sbc100** [comment] 2019-12-18 18:01
`sbrk` should be defined withing the wasm module and not by JS.  Its part of the libmalloc and the source code is in `system/lib/sbrk.c`.

Does you webassembly module load when you run it without using WebPack or this "wasm-loader" thing you are talking about?   If it does, what command line flags are you using when linking? 

Perhaps open a separate issue as this seem unrelated to the original topic.

**Comment by skandonkumar** [comment] 2019-12-18 19:38
Hi @sbc100 @kripken , I have created a new issue in the project regarding the error. If the problem is with WebPack, maybe should I use Rollup? Thank You for your assistance
