### ISSUE TITLE
Calling addFunction from C requires better documentation

### ISSUE THREAD

**Issue by abcthomas** [kripken/emscripten#6679] opened 2018-06-12 14:09 UTC
Since version 1.37.27 `Runtime.addFunction` has changed to a top level function `addFunction`. The previous version of the function could be called from C in the following way:
```
    // we call Runtime.addFunction from c++
    int f_ptr_int = val::module_property( "Runtime" ).call<int>( "addFunction", jsfunc );

    // it returns an int that we can reinterpret as a function pointer
    void( *fn )( const std::vector<std::string>& ) = reinterpret_cast< void( *)( const std::vector<std::string>& ) >( f_ptr_int );
```

However I'm unsure of how to convert this to the new format, simply leaving "Runtime" as a blank string doesn't work. The documentation no longer includes any code snippets or information on how to call this function from C: https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-functions-as-function-pointers-from-c

It also links to a very old test file that is no longer the same format in newer versions.

I'll happily update the documentation once I know how to actually call this now, I've seen val has a `global` static function but I'm unsure of whether that's the right thing to use. What is the correct way to now call this from C ?

**Comment by kripken** [comment] 2018-06-13 22:50
Thanks for filing!

Two changes are the issue here, I think: first, that function is not on the Runtime object anymore, which we removed, so it should be in the global scope. However, the optimizer may remove it from the global scope if it isn't used, and it can't see an embind usage in c++. To avoid that, the addFunction method needs to be exported using `EXTRA_EXPORTED_RUNTIME_METHODS`, see http://kripken.github.io/emscripten-site/docs/getting_started/FAQ.html#why-do-i-get-typeerror-module-something-is-not-a-function

A PR to fix the docs would be great! :)

**Comment by aheejin** [comment] 2018-06-13 23:11
I improved the documentation a bit in #6695. And the other thing is, as written in the documentation (the formatting is now messed up though), now you need to provide an extra string that describes the function's signature. This breaking change was introduced in v1.37.34.

So how you call `addFunction` from JS side is like
```
var newFuncPtr = addFunction(yourFunction, 'vi');
```
in case your function takes an int and does not return anything. I guess you need to change your C code to reflect this as well.

**Comment by abcthomas** [comment] 2018-06-14 09:42
Thanks for the replies, but I'm still a little confused on the calling convention from C++.

Assuming the function has been exported, how do we call a global function from C++ ?

`val::module_property( "" ).call<int>( "addFunction", jsfunc );`
or
`val::global("addFunction").call<int>("");`
or
`val::global("").call<int>("addFunction");`

Or something completely different ?

Thanks for the info on the extra parameters, I think it's only needed for the WASM back-end at the moment though.

**Comment by abcthomas** [comment] 2018-06-14 11:05
Ok after doing some digging I've found that the correct way to call is as follows:
```
    // we call addFunction from c++
    val f_ptr = val::global("addFunction")( jsfunc );
    // convert the pointer to an integer
    int f_ptr_int = f_ptr.as<int>();
```

Also it **must** be exported using `EXTRA_EXPORTED_RUNTIME_METHODS`. I'll create a PR for the docs when I get a chance

**Comment by aheejin** [comment] 2018-12-02 09:10
It looks like we can close this now.

**Closed by aheejin** 2018-12-02 09:10 UTC

**Comment by hardfist** [comment] 2021-05-17 10:47
It seems that val::global("addFunction") returns undefined even thou I setup EXTRA_EXPORTED_RUNTIME_METHODS=['addFunction']

**Comment by aheejin** [comment] 2021-05-17 22:44
Can you give a simple reproducer cpp file and the command line?

**Comment by hardfist** [comment] 2021-05-18 02:42
https://github.com/hardfist/wasm-bind @aheejin you can reproduce here, emcc@2.0.16

**Comment by hardfist** [comment] 2021-05-18 02:45
I actually use `val::module_property("addFunction")` to get addFunction, but it seems that `addFunction` only supports limits return type(`ijfd`) for wasm backend, if I want to support custom return type(struct for example), I have to use js backend which doesn't support dwarf debug yet, so is there any way to support custom returntype for wasm backend

**Comment by aheejin** [comment] 2021-05-18 03:15
I compiled main.cc using `emcc --bind main.cc -o main.js` and ran main.js and it exited without a problem. What is the expected behavior? What's not working? I'm using the latest trunk, but I'm not sure anything related has changed recently.

Also `addFunction` only support those types because they are the only basic types supported by wasm. How are you going to pass a struct to wasm?

**Comment by hardfist** [comment] 2021-05-18 03:19
> I compiled main.cc using `emcc --bind main.cc -o main.js` and ran main.js and it exited without a problem. What is the expected behavior? What's not working? I'm using the latest trunk, but I'm not sure anything related has changed recently.
> 
> Also `addFunction` only support those types because they are the only basic types supported by wasm. How are you going to pass a struct to wasm?

you should run node index.js other than node main.js

**Comment by hardfist** [comment] 2021-05-18 03:21
> I compiled main.cc using `emcc --bind main.cc -o main.js` and ran main.js and it exited without a problem. What is the expected behavior? What's not working? I'm using the latest trunk, but I'm not sure anything related has changed recently.
> 
> Also `addFunction` only support those types because they are the only basic types supported by wasm. How are you going to pass a struct to wasm?

But in real life project, I do need to pass callback from js to wasm, I just wonder is there any workaround other than change backend to js

**Comment by aheejin** [comment] 2021-05-18 03:29
```
$ node index.js
m: [Function: Test] { argCount: undefined }
hello world
```

Is this not the result expected?

> But in real life project, I do need to pass callback from js to wasm, I just wonder is there any workaround other than change backend to js

I am not an expert of JS-native code interaction in Emscripten, but there seem to be more than one ways of doing it: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html. Is there possibly anything else that is more suitable to your needs?

**Comment by hardfist** [comment] 2021-05-18 03:33
No, you can follow the readme
```
$ npm run build
$ node index.js
```
I think you don't run build first

**Comment by hardfist** [comment] 2021-05-18 03:35
My basic needs is
* pass an js callback to c++ class method
* convert the js callback to function pointer and assign to c++ function pointer
* call c++ function pointer and get result(an struct)

**Comment by aheejin** [comment] 2021-05-18 03:45
OK, I get an error now, but if I switch to `module_property`, it works. Then is that a problem?
I'm sorry, I worked on `addFunction` briefly a while ago but I don't have much knowledge in embind.

**Comment by hardfist** [comment] 2021-05-18 03:51
yes, there is no document about how get addFunction in c++, and the answer in this issue seems wrong for current version
