### ISSUE TITLE
error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')

### ISSUE THREAD

**Issue by akshay-hazari** [kripken/emscripten#5499] opened 2017-08-22 06:13 UTC
The example I have been trying to compile gets done via cmake which creates a cpp.o file.
The .js file created gives a corrupted heap memory area error. 

But when I try to run the compiled cpp.o code like this it shows.

./webcam_face_pose_ex.cpp.o
`error: Unknown attribute kind (52) (Producer: 'LLVM4.0.0' Reader: 'LLVM 3.8.0')`

clang -v on the system showed 3.8.0 

So I tried to install clang-4.0.0 by adding a ppa to apt-get and update-alternatives to use clang-4.0 on the system But it doesn't resolve the error.  

Is there a way to use LLVM3.8.0 in emscripten or any other way to solve it.

The .emscripten file reads like.
```
import os
LLVM_ROOT='/home/akshay/Downloads/emsdk-portable/clang/fastcomp/build_incoming_64/bin'
NODE_JS='/home/akshay/Downloads/emsdk-portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/home/akshay/Downloads/emsdk-portable/emscripten/incoming'
EMSCRIPTEN_NATIVE_OPTIMIZER='/home/akshay/Downloads/emsdk-portable/emscripten/incoming_64bit_optimizer/optimizer'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

Any help is appreciated,

**Comment by juj** [comment] 2017-08-22 06:31
This is a duplicate of https://github.com/kripken/emscripten/issues/5435#issuecomment-323738264, where we are already discussing the issue, so let's not make two copies of it.

**Closed by juj** 2017-08-22 06:31 UTC

**Comment by Rtoax** [comment] 2021-11-04 08:36
My problem: `error: Unknown attribute kind (61) (Producer: 'LLVM11.0.0' Reader: 'LLVM 7.0.1')`

when i `$ whereis opt`, get
```
$ whereis opt 
opt: /usr/bin/opt /etc/opt /usr/local/bin/opt /usr/share/man/man1/opt.1.gz
$ /usr/local/bin/opt --version
LLVM (http://llvm.org/):
  LLVM version 7.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
$ /usr/bin/opt --version
LLVM (http://llvm.org/):
  LLVM version 11.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake
```

i delete opt in `local`(`$ rm -f /usr/local/bin/opt`), the same as `llc` command. 
https://github.com/emscripten-core/emscripten/issues/5435

**Comment by sbc100** [comment] 2021-11-04 18:01
@Rtoax emscripten uses it own version of llvm / opt, and is likely not compatible with the system version (/usr/bin/opt etc).  We build and ship llvm tip-of-tree which is currently llvm-14 (i.e. an unreleased version).
