### ISSUE TITLE
EMULATE_FUNCTION_POINTER_CASTS and WASM=1

### ISSUE THREAD

**Issue by mdboom** [kripken/emscripten#6309] opened 2018-03-07 17:26 UTC
I'm trying to build Python with Numpy as part of iodide-project/iodide, an in-browser scientific computing notebook.

I have something that largely works with `asm.js`, but when I turn on `WASM=1` it fails to compile, spewing many wasm validation errors.  Output from the build is available [here](https://raw.githubusercontent.com/iodide-project/pyodide-demo/master/build.log) (85MB) Is this a known issue?

To reproduce, check out the `numpy` branch of iodide-project/pyodide, and edit the `Makefile` to add `-s WASM=1`.  You'll also need to apply my small patch to emscripten in #6308.

**Comment by kripken** [comment] 2018-03-07 21:26
Hmm, something definitely looks wrong here :) Thanks for filing!

First I opened https://github.com/WebAssembly/binaryen/pull/1463 for all those warnings. The PR should at least limit the amount shown.

Looking in the errors, it all seems to be fp emulation stubs that return a float and receive an integer, and don't bother to cast it. Strange that that doesn't work. Can you send me the `.asm.js` file, which is the input to the asm2wasm invocation that shows those errors? (if you build with `EMCC_DEBUG=1` in the env, it will save that file locally, or maybe just in `/tmp/emscripten_temp/` since it fails)

Also worrying in that output is that e.g. `_unicode_upper` is called with no param from all the fp emulation stubs. Then asm2wasm adds a zero to get validation to work (causing all those warnings). But the question is why it didn't send a parameter anyhow, so maybe those warnings are in fact indicating real problems. Looking in the `.asm.js` file may clear that up too.

**Comment by kripken** [comment] 2018-03-07 22:28
Actually, no need for the .asm.js file, I see I can reproduce this just by running the python test in the test suite, if I add `MAIN_MODULE=1`.

Still investigating, but definitely something wrong here, we have e.g. `instance_dealloc` take one param and return nothing, but the emulation functions look like
```
function fpemu_i_17() {
 ; return _instance_dealloc()|0
}
[..]
function fpemu_ii_17(p0) {
 p0 = p0|0; return _instance_dealloc()|0
}
```

**Comment by kripken** [comment] 2018-03-07 22:36
The issue is that `EMULATED_FUNCTION_POINTERS` in wasm mode puts all the functions in one table, discarding the asm.js type info. We used that info to sdt up the fpemu functions, and silently got meaningless data. Not sure yet how to fix this.

**Comment by kripken** [comment] 2018-03-07 22:53
Investigating, there isn't a trivial fix for this. The asm.js backend would just need to be improved to also emit metadata about function types for each function, and emscripten.py would need to parse that when computing `function_pointer_targets`.

Would be good to fix, but on the other hand asm.js does work with this currently, and in the long term wasm dynamic linking will probably change anyhow, so fixing this for wasm now would just be of temporary benefit, I think.

**Comment by kripken** [comment] 2018-03-08 18:26
Actually maybe we can just parse the types out of the asm.js. I'll look into that.

**Comment by aheejin** [comment] 2018-03-08 21:48
Not sure if this is relevant, but we are generating type signature information from wasm backend for `addFunction` support now. [Here](https://github.com/WebAssembly/binaryen/blob/be9243419302aca1ff088004546205f1c252f9c5/test/dot_s/reserved_func_ptrs.jscall.wast#L281) is an example metadata and [here](https://github.com/WebAssembly/binaryen/blob/be9243419302aca1ff088004546205f1c252f9c5/src/wasm-emscripten.cpp#L246-L298) is the function that generates it. Can we do something similar?

**Comment by kripken** [comment] 2018-03-08 23:25
@aheejin hmm, yeah, it's much more practical to find the signature in binaryen. Doing this in binaryen would also mean it works in the wasm backend. So that's a good idea.

But I'm actually not sure it can be done well at that level. The core problem in function pointer cast emulation is that we indirectly call a function `f` which has type `t` but the indirect call itself statically has type `u`. So we need to match up the number of parameters and their types (dropping extra ones, adding a zero of the right type for missing ones, etc.).

In asm.js, we have a separate function table for each type. For a particular index, normally all of the tables contain NULL, except for the table with the right type. In emulation mode we replace those NULLs with thunks that statically fix things up. So indexes don't need to change. And the overhead isn't too bad actually, just an extra direct call basically.

In wasm we just have a single table, though. If the table were of a fixed size then we could add an offset for each type, maybe, but assuming a fixed size would rule out dynamic linking which is the motivation in this issue here actually.

Another option might be to spill params to globals or the stack. Then the thunk could unspill them, add missing ones and ignore unneeded ones, and do the call. Seems like that could work but I worry it would be quite slow...

**Comment by kripken** [comment] 2018-03-09 17:51
Or, maybe we can limit the number of parameters, and have all indirect calls use the full number of them with i64, and the thunks would translate to the right thing for the target. That seems not terribly slow, so it could be good enough. I'll try it.

**Comment by kripken** [comment] 2018-03-10 00:31
Ok, I implemented this in `fcastemu` branches in binaryen and emscripten. It fixes the case of python in the test suite with `MAIN_MODULE`, which should mean it also fixes the original testcase here. Still running tests on CI though, will open PRs when this looks fully correct.

**Comment by kripken** [comment] 2018-03-15 19:07
Those branches landed so this should now be all fixed.

**Closed** 2018-03-15 19:06 UTC
