### ISSUE TITLE
js-optimizer emits empty if clauses

### ISSUE THREAD

**Issue by coolwanglu** [kripken/emscripten#3154] opened 2015-01-27 08:24 UTC
I managed to isolated the affected function:

```
// emcc-4-meminit.js
function _did_set_title__async_cb($0) {
 $0 = $0|0;
 var $1 = 0, $2 = 0, $3 = 0, $4 = 0, $5 = 0, $6 = 0, $7 = 0, label = 0, sp = 0;
 sp = STACKTOP;
 $1 = (($0) + 4|0);
 $2 = HEAP32[$1>>2]|0;
 $3 = ($2|0)==(0);
 if ($3) {
  $6 = HEAP32[122104>>2]|0;
  $7 = ($6|0)==(0);
  if ($7) {
  }
 } else {
  $4 = HEAP32[121416>>2]|0;
  $5 = ($4|0)==(0);
  if ($5) {
  }
 }
 STACKTOP = sp;return;
}

// emcc-5-js_opts.js
function Oqa(a){a=a|0;var b=0;b=i;if(!(c[a+4>>2]|0))else i=b;return}
```

This function is an async callback generated by ASYNCIFY, and it happens that the function does nothing.
Not sure why LLVM did not optimize this, but this looks like a bug in js-optimizer.

**Comment by kripken** [comment] 2015-01-27 19:01
Do you have the C source for that function? Or LLVM IR?

Which js optimizer passes are run on it? (`EMCC_DEBUG=1` will list them, you can paste the full output here, other parts might be interesting too). I tried `python tools/js_optimizer.py a.js eliminate simplifyExpressions simplifyIfs registerize asmLastOpts last` on latest incoming (which are you using?), and could not reproduce the problem.

**Comment by kripken** [comment] 2015-01-27 22:02
Ah, I can reproduce it if i plug in this function in emcc, but not in the js optimizer.

**Comment by kripken** [comment] 2015-01-27 22:11
The reason LLVM did not optimize your code, I suspect, is that asyncify happens *after* LLVM optimizations are run. During link, we just do things like asyncify, then generate code.

**Comment by kripken** [comment] 2015-01-27 22:41
Should be fixed now, please verify.

**Comment by coolwanglu** [comment] 2015-01-28 12:54
It works now, thanks for the quick fix!

But it's still not nature to emit a semicolon here, on the other hand it seems more intuitive to flip the condition and remove the empty else clause, or just emit the expression when both if and else clauses are empty. In the last case, the whole statement can be removed when the expression does nothing.

Do you think this should be done in the JS optimizer, or we should add more passes in LLVM to avoid such cases?

**Closed** 2015-01-28 12:55 UTC

**Comment by kripken** [comment] 2015-01-28 23:14
We could add it to the optimizer I suppose, as it could in theory happen even on optimized code. I doubt the code size waste is significant, though, so I'd say it's low priority.

**Comment by coolwanglu** [comment] 2015-01-29 07:23
Yeah I agree, not a big deal.
