### ISSUE TITLE
Unresolved symbol for duplicated file names

### ISSUE THREAD

**Issue by mad-rain** [kripken/emscripten#3168] opened 2015-02-03 10:00 UTC
Hi!

I have recently updated Emscripten from 1.27.0 to 1.29.0 and can't link my project now.

There are 2 files with the same file name and but different paths. Something like this:
   MyDirectory/MyFile.cpp
   MyDirectory/MyFile.h
   MyFile.cpp
   MyFile.h

It seems like an object file being generated from MyFile.cpp placed in root directory is completely ignored by the linker. I tried to rename the file and then everything linked successfully. I was able to reproduce the problem on Windows and OS X toolchains.

Any ideas how this could be resolved without renaming any files?

UPDATE:

I was able to reproduce the problem with minimal number of files:

http://www.filedropper.com/emscriptenlinkbug

Thanks.

**Comment by kripken** [comment] 2015-02-03 23:11
I had to rename `File.o` because it had a weird non-ascii character at the end. Perhaps that was the problem?

After doing that, on the incoming branch I can build the html without warnings or errors, and when I run it it prints out

````
CTest::File()
CTest2::File()
CTest2::File()
````

also without errors.

**Comment by mad-rain** [comment] 2015-02-04 05:24
Not sure what non-ascii character do you mean. I have checked all files in the zip file - non of them contain non-ascii symbols. I have created these files in Windows, that's why they have \r\n line endings.

**Comment by kripken** [comment] 2015-02-04 05:28
Not the contents of the files. That one file's name itself had a weird non-ascii character.

What specific error do you see btw? Is it during compilation or at runtime?

**Comment by mad-rain** [comment] 2015-02-04 05:38
I rezipped under OS X:
http://www.filedropper.com/emscriptenlinkbug2

This is what I see (please change paths in c.sh before launch):
macbookpro:EmscriptenLinkBug rain$ ./c.sh 
warning: unresolved symbol: _ZN5CTest4FileEv

**Comment by mad-rain** [comment] 2015-02-05 04:58
Any ideas?

**Comment by kripken** [comment] 2015-02-20 21:27
Based on mailing list discussion, looks like a duplicate of #2619

**Closed by kripken** 2015-02-20 21:27 UTC
