### ISSUE TITLE
pthread with emscripten

### ISSUE THREAD

**Issue by AppPlusPlus** [kripken/emscripten#3702] opened 2015-08-20 14:17 UTC
Hello,

I was using a very basic pthread program this morning. It was working with: 
`emcc -O2 USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=16 --std=c++11 hello.cpp -o hello.html`

Then I cloned the lastet version: ./emsdk install sdk-incoming-64bit

now with the same command, I get this:
`unresolved symbol: posix_spawn`
`unreloved symbol: posix_spawn_file_actions_adddup2`
`...`

1- Although they are "warning"s, I wan to know what went wrong?
2- I want to know if it is possible to compile the code with a large number of threads, I couldn't go more than 20 (32 takes forever to run!)

**Comment by juj** [comment] 2015-08-20 17:34
Indeed, I can reproduce. This new warning message is a false positive, and it's due to a recent refactoring. In the current test suite, building

    em++ tests\pthread\test_pthread_create.cpp -s USE_PTHREADS=1 -O2 -s PTHREAD_POOL_SIZE=16 -std=c++11 -o a.html

will generate the warning. The culprit comes from the function `popen` that is referred to by our `_do_call` message proxying code. `popen` calls to `posix_spawn` and the others. I also see a warning message to unresolved `mkport` function.

Currently Emcripten threading support does not allow spawning new processes. I suppose it might be a somewhat geeky project to attempt to simulate processes as new tabs in the browser, or as a new thread that doesn't share memory area, but I can't think outright that it would be useful.

I am leaning on removing support altogether for the `popen` and `pclose` functions, and making those functions no-ops when building via Emscripten. Marked down https://github.com/kripken/emscripten/pull/3704 to at least drop referring to them in proxied code.

The 20 thread limit is mentioned in the documentation at https://github.com/kripken/emscripten/blob/incoming/site/source/docs/porting/pthreads.rst , which says "For web security purposes, there exists a fixed limit (by default 20) of threads that can be spawned when running in Firefox Nightly. #1052398 <https://bugzilla.mozilla.org/show_bug.cgi?id=1052398>. To adjust the limit, navigate to about:config and change the value of the pref "dom.workers.maxPerDomain"."

**Comment by kripken** [comment] 2015-08-20 18:50
Sorry about those warnings, they are now fixed on incoming.

**Closed** 2015-08-21 09:24 UTC
Labels: multithreading
