### ISSUE TITLE
Using std::cout before main has been entered

### ISSUE THREAD

**Issue by Zekian** [kripken/emscripten#3824] opened 2015-09-28 15:51 UTC
Some of the c++ standard library appears to unusable before main has been entered.
Printing a string seems to have no effect.
Printing a new line with `std::cout << std::endl;` causes an interger to be printed and then the program to terminate.

```C++
#include <iostream>

class A {
public:
  A() {
    std::cout << "bug";
    //std::cout << std::endl;
  }
};

A a;

int main() {
  std::cout << "free code" << std::endl;
  return 0;
}
```

When I compiled this with clang it outputs "bugfree code" and when I compiled it with emscripten it outputs "free code".

**Comment by kripken** [comment] 2015-09-28 22:41
Very strange. LLVM emits

````
@llvm.global_ctors = appending global [2 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__sub_I_a.cpp, i8* null }, { i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__sub_I_iostream.cpp, i8* null }]
````

And [langref](http://llvm.org/docs/LangRef.html#the-llvm-global-ctors-global-variable) says "The order of functions with the same priority is not defined." Which means that the iostream constructor can happen after A's constructor, which is why this is broken.

@sunfishcode, is LLVM doing the right thing here? Is this undefined behavior perhaps?

**Comment by kripken** [comment] 2015-09-28 22:42
Or perhaps does libc++ need to raise the priority of it's global constructors?

**Comment by sunfishcode** [comment] 2015-09-28 23:48
I don't remember if cout is guaranteed to be initialized before static constructors that use it, and the language in the C++ standard is eluding me at the moment. However the standard does at least have the footnote "If it is possible for them to do so, implementations are encouraged to initialize the objects [cout etc] earlier than required." so if it's not difficult to raise the priority of these global constructors, it would be good to do so.

**Comment by kripken** [comment] 2015-09-29 19:57
Thanks, I'll find out how to do that.

**Comment by kripken** [comment] 2015-09-29 20:31
Fixed on incoming.

**Closed by kripken** 2015-09-29 20:31 UTC

**Comment by kripken** [comment] 2015-09-29 20:32
I suppose the reason we see this is that natively, libcxx is normally linked as a library, and the system makes sure to run linked library global constructors first, while for us, we merge all the code as bitcode first, so libcxx constructors are in no special position.

**Comment by ldionne** [comment] 2020-05-14 13:56
Hi. Libc++ maintainer here. I want to fix this issue, but I don't know how to test it -- I can't reproduce the issue on mac os. Any idea about how I could reproduce this on non-emscripten? What's special about static constructors in emscripten that make this fail?

**Comment by kripken** [comment] 2020-05-14 17:39
@ldionne Thanks! There might not be anything to fix in libc++, though I'm not sure. We fixed this locally with https://github.com/emscripten-core/emscripten/commit/25ddbe8694824de514230b4386097909e7714877 which adjusts the priority of the constructor. That includes a testcase that failed before but passes with the fix.

I'm not sure why that isn't necessary on other platforms, but one big difference is emscripten links in libc++ statically, and it's treated as just normal code that is linked in at that point. So it "competes" with all other global ctors, and without a special priority it can "lose" and run too late. Perhaps normally the dynamic linker on a native system would initialize libraries before user code that uses the library, which would avoid this being an issue. Maybe static linking on mac os, or static + LTO, could reproduce the issue.

**Comment by ldionne** [comment] 2020-09-16 17:20
This issue should be fixed now by https://reviews.llvm.org/D31413.
