### ISSUE TITLE
NODEFS won't work when using --closure 1

### ISSUE THREAD

**Issue by julien33** [kripken/emscripten#3230] opened 2015-03-05 16:47 UTC
NODEFS calls to Node FileSystem functions are replaced by short names, which cause the whole thing to fail :

R.Xa instead of R.lstatSync
R.fa instead of R.writeSync
...
also, the output results of lstatSync are remapped from the original structure to a new structure, but the names are scrambled and therefore nothing work as expected.

setting closure to 0 fixes everything.

This problem was encountered while trying to recompile sql.js from https://github.com/kripken/sql.js/

**Comment by kripken** [comment] 2015-03-09 20:21
Is this from normal JS in an EM_ASM or something like that? Which code is trying to find writeSync, and not finding it?

**Comment by julien33** [comment] 2015-03-09 21:07
In fact I tried to compile your project sql.js (https://github.com/kripken/sql.js) and add support for direct file access using a NODEFS mounting point, but the resulting JS didn't work under node.js.

If I remove the closure optimization it does work, after hours tring to understand where was the problem, and by comparing side by side the unobfuscated debug code and the obfuscated optimized code, I noticed that using closure rename every variable name, including the calls to node.js native File System module, also, even by renaming by hand all the required function (lstatSync, openSync, closeSync, ...), the result from lstatSync wasn't compatible as the code tried to read the obfuscated member names from it.

So I think there must be a simple way to teach emscripten to know that members from node.js native modules are not to be scrambled, and generally to avoid renaming members from native API (browser / node.js / ...)

**Comment by kripken** [comment] 2015-03-11 18:57
Well, closure should be fine to run on a codebase - the problem is when code from *outside* tries to access it. Code that wasn't minified together, will see minified names it can't understand.

So the question is which code is trying to do those calls. If it's other code on the web page, or code from an EM_ASM block, etc., each of those has a different solution.

It's also an option to not use closure. It helps reduce code size, but in large-enough projects, it doens't matter too much - might be worth measuring here (with and without gzip).

**Comment by Kagami** [comment] 2015-07-19 16:51
Hi. The problem is in this module: https://github.com/kripken/emscripten/blob/master/src/library_nodefs.js (search for "fs."). Closure minifies calls to Node's fs module and now it's impossible to use NODEFS and `--closure 1` emscripten option at all.

I'm not too familar with Closure but it can be fixed by e.g. using `fs["lstatSync"]` instead of `fs.lstatSync` and so on. I can file a PR if you have no objections against that type of fix.

**Comment by Kagami** [comment] 2015-07-20 09:44
Also, closure-enabled builds result in different behavior here: https://github.com/kripken/emscripten/blob/1.34.3/src/library_tty.js#L107

**Comment by kripken** [comment] 2015-07-20 17:49
Yes, quoting is the correct fix for this - a pull request would be great.

**Comment by Kagami** [comment] 2015-07-22 19:57
I think this can be closed since https://github.com/kripken/emscripten/pull/3629 was merged?

**Comment by kripken** [comment] 2015-07-22 20:04
Yes.

**Closed by kripken** 2015-07-22 20:04 UTC
Labels: filesystem
