### ISSUE TITLE
All Windows installers (NSIS) after 1.5.6.2  take an exorbitant amount of time to install and uninstall for Windows 10

### ISSUE THREAD

**Issue by balmyBanzai** [kripken/emscripten#3974] opened 2015-12-19 07:41 UTC
I actually registered with GitHub just to write this bug :x No Win10 love? :)

Frequency: 100%

STEPS TO REPRO
1. With a stopwatch of any kind, and Windows 8.1
2. Record the duration of installing
3. Record the duration of uninstalling
4. With a stopwatch of any kind, and Windows 10
5. Repeat Step 2 and step 3

BEHAVIOR
When installing or uninstalling emscripten using the NSIS installer for Windows, on Windows 10 for any version after 1.5.6.2 (current latest is 1.35.0) the duration required to successfully complete installing and uninstalling is substantially longer than installation and uninstallation durations on Windows 8.1. Windows 8.1 Home was used for performance comparison.

As there is no activity indicator for NSIS, the installer appears to have failed which would require the task manager or other non-UX friendly methods to terminate the installer (gray X and Cancel/Close, RC-Close doesn't work) which makes this seem to be some sort of installer crash on first inspection

EXPECTED BEHAVIOR
Installation / uninstallation times not noticeably different from Windows 8.1 on equivalent hardware.

RECORDED RESULTS (v1.35.0)
Windows 8.1 Install Duration: **01:50**
Windows 8.1 Uninstall Duration: **00:28**

Windows 10 Install Duration: **16:35**
Windows 10 Uninstall Duration: **12:59**

Notes:
-Identical hardware for all tests
-Only real installations of Windows used on physical machines
-Mostly identical software loaded on both Windows 8.1 and Windows 10 for the test systems used
-Windows 10 Pro and Windows 10 Enterprise verification checks were done on different physical machines
-Could not be reproduced on 1.5.6.2 and earlier for both 32 and 64 bit versions.
-Occurs with both online and offline NSIS installers
-Verified on the following OSs:
-- Windows 10 Enterprise
-- Windows 10 Pro
-Verified on the following releases: 
-- 1.35.0
-- 1.27.0
-- 1.12.0
-- 1.7.8

helpful search words: installer, uninstaller, win10, win81, win8.1, nullsoft, scriptable, install, system hang, soft crash, timeout, delay, freeze, froze, frozen, user experiece

**Comment by juj** [comment] 2015-12-29 15:02
Thanks for reporting. I tried timing the installation of Emscripten 1.35.0 offline NSIS installer on my Windows 10 box, and I got 1 minute 10 seconds to install, and 13 seconds to uninstall.

When the installation hangs for you, what does the UI of the installer show at that time? Does it hang in one frozen spot, or is there some (very slow even) periodical update being displayed?

Perhaps Windows Defender or some other antivirus might be interfering? What does Windows task manager show for disk and cpu activity % at the time of the hang? Are the system processes idle, or is there some process consuming 100% of a system resource?

**Comment by cabbruzzese** [comment] 2016-02-12 12:00
I'm having the same problem but in my case it is NSIS installers that I've generated for a completely different project.The installers hang and are unresponsive. Sometimes even the generation of an installer crashes.

Turns out to be an anti virus problem. Also, this is clearly a bug with the Nullsoft installer software or the anti virus vendors. Not with the project at hand.

**Comment by balmyBanzai** [comment] 2016-09-08 19:52
@cabbruzzese I tried a couple different anti-viruses, including McAfee and Windows Defender. If it's an anti-virus issue, I couldn't find a way to stop the behavior.

I don't normally have these issues with NSIS installers so pointing to Nullsoft is a dubious claim, but right now it's no less valid than EMScripten's installer config possibly causing the issues.

**Comment by cabbruzzese** [comment] 2016-09-08 20:06
Not just dubious, but totally misleading! :P 

What I meant to say was that I had to add the installer to the anti-virus exception list in order to finish. Disabling the anti-virus for a short period of time also worked. 

It had previously worked on windows 10 but an unknown update during the course of several months caused the problem to appear on a different project. So it's not specifically NSIS, the anti-virus, or windows 10. It was the combination of all 3. Just figured I'd share a work around that had worked for the time.

I have not had to build my particular installer again in quite some time, so I don't know if the problem is resolved.

**Comment by juj** [comment] 2016-09-09 14:36
Hmm, I've installed Emscripten SDK on a couple of Windows 8 and Windows 10 devices, which each have Windows Defender enabled (but no external antivirus software). On all of those systems, there weren't any performance problems in installing.

I don't have a fix if this kind of thing occurs for someone, but I'll close this with a workaround: people should be able to install the portable emsdk version then which does not rely on NSIS, or for that matter, installing anything to Windows registry or Program Files. The portable installer only does git and zip operations via a python script, so that will avoid all interactions with NSIS.

**Closed by juj** 2016-09-09 14:36 UTC
Labels: windows

**Comment by balmyBanzai** [comment] 2016-09-09 18:31
Sounds good, @juj ! Thanks again for following up, @cabbruzzese
