### ISSUE TITLE
Warnings when linking (very likely Windows only)

### ISSUE THREAD

**Issue by iboB** [kripken/emscripten#3760] opened 2015-09-09 12:42 UTC
This started in Windows with 1.34.6 and it still true with 1.34.7 (I haven't tested it on other platforms yet). Every time when linking I get the exact same warning three times:

```
warning: unexpected number of arguments 3 in call to 'strtold', should be 2
warning: unexpected number of arguments 3 in call to 'strtold', should be 2
warning: unexpected number of arguments 3 in call to 'strtold', should be 2
```

This is true for a small "hello world" application and for bigger projects with hundreds of files. Every time these three lines are printed when linking.

**Comment by emilydolson** [comment] 2015-09-09 16:03
I am getting the same problem in Linux (Mint 17 Cinnamon 64-bit, in case it matters). I just updated to 1.34.7.

I seem to only get the warnings if I use std::cout. If I don't print anything, or use printf(), all is well.

**Comment by kripken** [comment] 2015-09-09 21:27
Thanks, I see it on linux as well, when using std::cout. Looks like that ends up using `strtod_l`, where the problem is. The musl libc seems to just alias the locale and non-locale versions even though they have a different number of parameters.

Fixed on incoming and added a test, thanks @iboB and @emilydolson.

**Closed by kripken** 2015-09-09 21:27 UTC
