### ISSUE TITLE
Emscripten output static libs as archive (.a) instead of bitcode (.bc) when using CMake toolchain file

### ISSUE THREAD

**Issue by gouletr** [kripken/emscripten#3731] opened 2015-09-01 18:27 UTC
As found in [this discussion thread](https://groups.google.com/forum/#!topic/emscripten-discuss/XBTwP5jn4dk), the CMake toolchain file that is provided with Emscripten will setup the static library create command to use `emar` instead of `emcc`, effectively creating archive (.a) files instead of bitcode (.bc) files.

This is problematic since archive (.a) files have the limitation that source files with same name will be duplicated because it only uses the file basename without considering the file path.

I was able to work-around this by modifying the `Emscripten.cmake` file to use `emcc` instead of `emar`, but perhaps we should either add an option to choose between the two, or entirely ditch the use of `emar` in that context? Another option would be to modify the `emar` python script to check for the output file extension and have it redirect to `emcc` if `extension == ".bc"`?

Is there any valid use cases to use `emar` instead of `emcc` to create static libraries? From what I understand, bitcode (.bc) files have much less limitations without sacrificing any features, so what is the point of using archive (.a) files anyway?

**Comment by juj** [comment] 2015-09-02 13:43
The reason that `emar` is used is due to parity with native. CMake scripts can invoke `CMAKE_AR` to perform archiving commands, and the intent is to have identical static linking support with native. If your program compiles and links correctly natively with using `.a` files, I don't think the problem is there, but we have some other discrepancy with how static linking works in Emscripten versus to native.

If you want to target `.bc` files instead of `.a` files, I believe you should be able to do something like

    if (EMSCRIPTEN)
        set(CMAKE_AR "emcc" CACHE)
        set(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")
        set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> -o <TARGET> <LINK_FLAGS> <OBJECTS>")
        set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> -o <TARGET> <LINK_FLAGS> <OBJECTS>")
    endif()

in the beginning of your CMakeLists.txt to force to use .bc files. If that is useful, we might add an Emscripten-specific CMake command line option or directive to specify this easily? However the root cause sounds like a bug in our underlying .a handling, if the linking does work correctly in native clang.

**Comment by gouletr** [comment] 2015-09-02 13:51
The archive files themselves work correctly, except if you have duplicate entries, which can happen more often with larger projects, resulting in unresolved symbols at link time.

I don't mind adding a few lines in my own CMakeLists.txt file, but I thought this might be useful to many of us. I think others also reported that they can't find their .bc files when building with CMake, and this is most likely the root cause of their issue.

**Comment by juj** [comment] 2015-09-02 13:54
I think duplicate entries work ok in native linking, and a .a file can contain e.g. 100 `file.o`s. Does your project not link correctly with `.a` files natively either?

**Comment by gouletr** [comment] 2015-09-02 13:56
Nope it doesn't, and the warning it generates is very clear: when duplicate entries are found, only the last one is kept, resulting in undefined symbols. Using .bc files solved it for us.

**Comment by kripken** [comment] 2015-09-02 15:09
@gouletr: Btw, as of 1.32.5 we have a workaround in emar to augment the basenames with a hash, to avoid basename collisions - which version do you see the problem on? If it's 1.32.5 or later, we might have a bug in that hash code, a testcase would be helpful.

**Comment by gouletr** [comment] 2015-09-02 15:16
I'm on incoming, commit 108797d366f4e0ee8fab90908310736665c8b103. I don't have a quick test case to provide since this is pretty large private code base, but I guess you can simply create something like this and it should reproduce:

static library foo:
bar1/bar.cpp
bar2/bar.cpp

Make sure the two source files provides different symbols that are needed by the program, and then just link that static lib with an executable.

**Comment by juj** [comment] 2015-09-02 16:57
@gouletr : which version of native compiler are you using? Tested this on Windows on mingw64 toolchain with g++ 4.8.3 and GNU ar 2.24, and on a linux with the current Emscripten fork of Clang (clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang a1c15194e1460ab8c5f1df8a8b220ad4b2eda8fe) (https://github.com/kripken/emscripten-fastcomp d718c3450d4fcbc5b232d6d10bf5eeb8f7cf44b3) and corresponding llvm-ar. On both duplicate files are ok, so this looks like an Emscripten-specific issue.

The test project I used is available here: https://dl.dropboxusercontent.com/u/40949268/emcc/lib_test.zip

Build with:

    mkdir ~/lib_test/
    cd ~/lib_test/
    wget https://dl.dropboxusercontent.com/u/40949268/emcc/lib_test.zip
    unzip lib_test.zip
    mkdir build
    export CC=/path/to/clang/fastcomp/build_incoming_64/bin/clang
    export CXX=/path/to/emsdk/clang/fastcomp/build_incoming_64/bin/clang++
    cmake .. -DCMAKE_AR=/path/to/emsdk/clang/fastcomp/build_incoming_64/bin/llvm-ar
    make

works correctly. Looking at the generated .a file, it contains `a.cpp.o` twice, which is not an issue:

	clb@Giada:~/lib_test/build$ llvm-nm static_lib/libstatic_library.a

	a.cpp.o:
	0000000000000000 T _Z3foov
	                 U printf

	a.cpp.o:
	0000000000000000 T _Z3barv
	                 U printf

@kripken: why was duplicate filenames an issue for Emscripten?

**Comment by gouletr** [comment] 2015-09-02 17:15
Your test code is correct. That should have reproduced it. Not sure why it works on your side. We use NMake to build instead of MinGW, but that shouldn't be an issue.

As for clang version... I didn't install a specific version of clang, it just came with the download. I first downloaded the latest portable emsdk 1.34.1 zip that's on your website. Then I ran this to get a build based on incoming branch:
```
emsdk update
emsdk install --build=Release sdk-incoming-64bit
emsdk activate --build=Release sdk-incoming-64bit
```

Running `llvm-ar --version` of this build prints the following:
```
  LLVM version 3.7.0svn
  DEBUG build.
  Built Aug 31 2015 (10:23:38).
  Default target: x86_64-pc-windows-msvc
  Host CPU: ivybridge
```

Our code base builds just fine with all other platforms that are using archive files (.a), such as Android, PS4, etc. As you say, this is specific to Emscripten.

**Comment by kripken** [comment] 2015-09-02 17:49
@gouletr: Strange. We have `other.test_identical_basenames` which tests what you describe, and passes. Something must be different in your build system somehow. Does that test pass for you?

@juj: Identical basenames are a problem for two reasons. First, the .a format ignores paths and just stores the basenames. That's not too bad by itself, but the second issue is that llvm-ar does *not* provide a way to extract both duplicates. You specify a name, and get the last one. llvm-ar used to have the ability to do this properly, but it was removed because it was nonstandard and not tested, and apparently no one complained ;)

**Comment by gouletr** [comment] 2015-09-02 20:22
It does pass, so I don't know why a similar setup would fail in a larger project.

**Comment by kripken** [comment] 2015-09-02 21:33
Can you provide the source code and build instructions to your project? I'd really like to find out why this is breaking in this case.

**Comment by gouletr** [comment] 2015-09-02 21:37
Unfortunately no, this is a commercial software; can't give out source code. :(

**Comment by kripken** [comment] 2015-09-02 21:50
Ok, no problem. If you do find a standalone testcase later that shows your project's issue, let's reopen this. For now, closing since nothing else we can do.

**Closed by kripken** 2015-09-02 21:50 UTC
Labels: CMake

**Comment by juj** [comment] 2015-09-03 12:57
" the second issue is that llvm-ar does not provide a way to extract both duplicates. You specify a name, and get the last one.": Why do we need to extract the files in the archive? Isn't there a way to get all the symbols? At least llvm-ar is able to dump all the symbols in the archive even with duplicates, so perhaps we could avoid it by not looking up by file like llvm-ar does? Or is that not possible somehow? I suppose this is not as critical since we have the hashing in place, but the hashing is not currently enabled on Windows when absolute path names/files on multiple paths are present, which could be a source of mysterious errors.

**Comment by gouletr** [comment] 2015-09-03 14:00
Ah that must be the issue, we're doing our builds on Windows.

**Comment by kripken** [comment] 2015-09-03 18:58
We need to extract the files in order to link: llvm-link cannot receive .a files. It wants just bitcode, so we implement the .a aspects ourselves. For that, we just want to get all the object files inside it, but llvm-ar just doesn't do it properly when there are duplicate basenames. It tramples the first with the later one.

I don't see the hashing disabled in any case but when the hashes collide, which should practically never happen?

**Comment by gouletr** [comment] 2015-09-03 19:33
Well I don't know what to say about this, all I know is that it reproduce 100% with our game engine code. Switching to .bc files fixed it for us (and .bc files seems to be smaller anyway) so it doesn't really matter. I think it just needs to be documented.

**Comment by kripken** [comment] 2015-09-03 20:21
I added some docs on incoming.

**Comment by gouletr** [comment] 2015-09-04 14:56
Thanks. :+1:

**Comment by lowdesertpunk** [comment] 2016-05-12 15:18
Bumped into the same issue.

Why it doesn't work because CMake generates an ar command the object files are passed in a `@file` argument. The fix https://github.com/kripken/emscripten/issues/2142 will just hash this file with the untouched contents inside.

```
emar: ['/Users/spacecadet/bin/emsdk/emscripten/tag-1.34.1/emar', 'rc', 'libfoo.a', '@CMakeFiles/foo.dir/objects1.rsp']   ==>   ['/Users/spacecadet/bin/emsdk/clang/e1.34.1_64bit/llvm-ar', 'rc', 'foo.a', '@CMakeFiles/foo.dir/objects1.rsp']
```

**Comment by gouletr** [comment] 2016-05-12 15:24
@lowdesertpunk nice catch! I knew I wasn't crazy after all. Thanks!

**Comment by rkaminsk** [comment] 2016-11-06 18:22
Hi, I ran into exactly the same problem. My workaround is to comment out the SET(*RESPONSE_FILE* 1) lines. Could you add an option to the file to enable/disable these lines? This is completely optional anyway, right?

**Comment by juj** [comment] 2016-11-13 19:38
The hashing feature should work in conjunction with response files, this sounds like a response file bug then. Does anyone have a small test case that could be added here? We could perhaps add an option to disable response files, but sounds like we should instead fix these two features to work together if that is possible.

**Comment by simondass** [comment] 2017-07-26 11:46
I seem to have this problem too if using response files.
The issue is in the emar script
`shutil.copyfile(orig_name, full_newname)`
Will fail due to the '@' character in the path so we will not have hashing which can eventually result in linker failure through undefined symbols. 
We could do something like change this to
`shutil.copyfile(orig_name.replace(CMAKE_C_RESPONSE_FILE_LINK_FLAG, ''), full_newname)`
and
`full_name = os.path.abspath(orig_name)`
to
`full_name = os.path.abspath(orig_name.replace(CMAKE_C_RESPONSE_FILE_LINK_FLAG, ''))`

**Comment by n0clu3** [comment] 2017-08-23 08:24
@simondass https://github.com/kripken/emscripten/pull/5505 this fixed the problem for me.
With this change emar takes the list of object files from the response file, add hashes to them similarly to as if they would be passed directly as input files. Then modifies(rewrites) the response file with the paths to the new files.

**Comment by kornerr** [comment] 2017-10-10 19:59
I have the same duplicate error when using 1.37.21.

**Comment by kornerr** [comment] 2017-10-10 20:17
I fixed the problem by using my old FastBuild.cmake script that merges several cpp into one (by simply producing single cpp that #includes other cpp files).
Here's [CMakeLists.txt](https://bitbucket.org/ogstudio-games/memory-colors/src/c6a10318d34dfd7d9933212333da85645264b32c/CMakeLists.txt?at=default&fileviewer=file-view-default) and here's [FastBuild.cmake](https://bitbucket.org/ogstudio-games/memory-colors/src/c6a10318d34dfd7d9933212333da85645264b32c/FastBuild.cmake?at=default&fileviewer=file-view-default). 

As a bonus building single source file is faster than several.

**Comment by rkaminsk** [comment] 2017-10-10 20:39
Combining into a single source file might not work for all projects. I resolved this by adding the following to the beginning of my root cmake file to unset the variables set in emscripten's tool chain file: 
```cmake
unset(CMAKE_C_USE_RESPONSE_FILE_FOR_LIBRARIES)
unset(CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES)
unset(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS)
unset(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS)
unset(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES)
unset(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES)
```
