### ISSUE TITLE
Installing on Linux failing. Unrecognized option '-std=c++11'

### ISSUE THREAD

**Issue by samsamm777** [kripken/emscripten#3203] opened 2015-02-20 14:48 UTC
I'm having trouble installing on linux. Using the command ` $ ./emsdk install latest`

``` bash
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/optimizer.dir/optimizer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/optimizer.dir/simple_ast.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/optimizer.dir/parser.cpp.o] Error 1
make[1]: *** [CMakeFiles/optimizer.dir/all] Error 2
make: *** [all] Error 2
Build failed due to exception!
Working directory: /mnt/nethome/users/***/Downloads/emsdk_portable/emscripten/master/tools/optimizer_build
Command '['make', '-j23']' returned non-zero exit status 2
Installation failed!
```

This is the gcc version i have.
``` bash
 $ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by juj** [comment] 2015-02-20 14:51
This looks like a duplicate of #3189, so let me close this here, and let's continue the conversation in the other thread.

**Closed by juj** 2015-02-20 14:51 UTC
