### ISSUE TITLE
Embind default function parametrs not work

### ISSUE THREAD

**Issue by MegaJsTeam** [kripken/emscripten#4143] opened 2016-03-04 18:17 UTC
in C++
```cpp
void ololo(int age = 10){}
```

in javascript:
```javascript
ololo() // throw embind error: function ololo request 1 parametr but call with 0
```

**Comment by juj** [comment] 2016-03-07 14:31
Closing as duplicate of #604.

**Closed by juj** 2016-03-07 14:31 UTC
Labels: embind
