### ISSUE TITLE
_mm_movemask_ps does not handle NaNs correctly

### ISSUE THREAD

**Issue by janezz55** [kripken/emscripten#3403] opened 2015-04-24 08:39 UTC
Say you put 4 NaNs into a __m128, _mm_movemask_ps() will return 0, which is not what happens on a real SSE machine. A NaN may have an arbitrary sign bit, which should be extracted, as specified. The rationale for allowing NaNs is, that a person might well use this intrinsic to extract signs from an integer vector, the integers in which might be interpreted as NaNs (even though they are not, they are integers). This is how I found out about this bug. I am using nodejs as my environment.

To test:

_mm_movemask_ps(_mm_set_epi32(-1, -1, -1, -1)) will be 0, but is 0xf on a real machine.

**Comment by juj** [comment] 2015-04-24 08:55
These types of issues are due to NaN canonicalization in JS engines. This is similar, but possibly not a duplicate of https://github.com/kripken/emscripten/issues/2791 ? Can you post a test snippet like in bug #2791 to check this? Also, which JS environment are you using? Note that the SIMD-JS polyfill will not be able to work with this.

**Comment by janezz55** [comment] 2015-04-24 08:59
It is certainly not a duplicate, I'd be able to tolerate the negative zero corner case. It is simply not SSE-compliant behavior, that will surely break code.

**Comment by juj** [comment] 2015-06-20 17:44
Sorry for the long delay. Coming back to this, now that I'm implementing SSE2 support to Emscripten.

Traditionally JS engines do not support the different bit patterns as NaNs, but they just have one canonical bit pattern that is a qNaN and all the other bits are destroyed in computations. Historically someone thought it would be clever to reserve the NaN bits in floats for the JS engine so that it can stuff special meaning to them. This is quite sad indeed for native parity, and as you can see from the other issues in this tracker, we are struggling with this a lot when adding SIMD support. It is not a SSE issue directly, but just a direct IEEE 754 floating point spec noncompliancy - JS floats are far from proper IEEE float behavior :/ 

Nevertheless, we have hope here, since in SIMD.js, once we have stuffed bits to a SIMD register, SIMD ops themselves won't destroy NaNs. Therefore it should be possible to support `_mm_movemask_ps`. I've added a test case for your case in the above commit, and I can see it passes in a `-O0` debug build, when run in Firefox Nightly or in SpiderMonkey. Unfortunately it does not run in node.js or any browser that polyfills SIMD support, since the polyfill won't be able to preserve NaNs.

Currently the code you posted fails in `-O1` and higher, due to another issue in LLVM/Clang, where the compiler does not know that floats can't preserve bits, and it over-eagerly optimizes the code to a bad form. In debug build, the following gets emitted, which is good and works:

	 $10 = SIMD_int32x4($6, $7, $8, $9);
	 $5 = $5;SIMD_int32x4_store(HEAPU8, $5, $10);
	 $11 = SIMD_int32x4_load(HEAPU8, $5);
	 $12 = SIMD_float32x4_fromInt32x4Bits($11);
	 $0 = $0;SIMD_float32x4_store(HEAPU8, $0, $12);
	 $13 = SIMD_float32x4_load(HEAPU8, $0);
	 $14 = $13.signMask;
	 $a = $14;

but in release build, the compiler gets too smart, and emits a buggy form which has lost the bits:

     $0 = SIMD_float32x4_splat(Math_fround(nan)).signMask;

This should be fixable in the compiler, by making it avoid such optimizations that aren't NaN-safe.

**Comment by juj** [comment] 2015-09-18 14:11
Fixed in incoming.

**Closed by juj** 2015-09-18 14:11 UTC
Labels: SIMD
