### ISSUE TITLE
Warning on invalid exported runtime methods should be shown even when assertions are off

### ISSUE THREAD

**Issue by Auron52** [kripken/emscripten#6581] opened 2018-05-24 22:07 UTC
Steps to Reproduce:
- Build the attached sample with the latest incoming Emscripten or look at the .js in the Output folder.
- Note that stringToUTF16 is not exported despite being included in the EXTRA_EXPORTED_RUNTIME_METHODS list

Previous tests on my side have revealed that 
1. If all spaces within EXTRA_EXPORTED_RUNTIME_METHODS are removed everything works as expected.
2. All subsequent entries after the first space within EXTRA_EXPORTED_RUNTIME_METHODS  are ignored.
3. EXPORTED_FUNCTIONS still works correctly even with spaces.

Thanks,

David

[AnimalLibraryCommandLineBug.zip](https://github.com/kripken/emscripten/files/2037248/AnimalLibraryCommandLineBug.zip)

**Comment by kripken** [comment] 2018-05-24 23:05
I think this might be a regression from #6436. cc @DJMcNab

**Comment by DJMcNab** [comment] 2018-05-25 06:26
Sorry! I obviously didn't think through my list parser thoroughly enough. I'll have a look tonight. 

Thanks for providing the sample. I'll see if I can work out what's wrong when I can.

**Comment by DJMcNab** [comment] 2018-05-30 05:39
Yeah, I probably should try to debug that. Unfortunately I am on a windows host and so am having trouble running the cmake stuff (no experience working with C++ either)

No, it didn't handle multiple argv members, but it did handle quoted strings with commas in lists correctly. The issue with using multiple argv members is that I'm not sure how I would increase the outer `i` counter variable. I will probably seen if I can implement reading multiple argv members.

**Comment by Auron52** [comment] 2018-06-01 18:05
Hmm, looks like I got bitten by a peculiarity of CMake.... This is the command line it runs:
emcc -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_FUNCTIONS="['_ANM_GetAge','_ANM_SetOwnerName','_ANM_CatCreatePersian', '_ANM_CatCreateScottishFold','_ANM_CatGetMeowIntensity','_ANM_CatGetSoftnessFactor','_ANM_CatGetWhiskerLength','_ANM_CatGetClawLength']" -s EXTRA_EXPORTED_RUNTIME_METHODS=['UTF16ToString',;'stringToUTF16'] -Oz libanimal_library.so --bind --llvm-lto 3 -s NO_EXIT_RUNTIME=1 -s TOTAL_MEMORY=50331648 -s RESERVED_FUNCTION_POINTERS=10 -s WASM=1 -s BINARYEN_METHOD='native-wasm' -o AnimalLibrary.js

As you can see it replaces the space with a ';' thereby leading to the problem. (incidentally this also explains why EXPORTED_FUNCTIONS was working since cmake will not do this silliness when the result is quoted. Overall while it might be nice to have the parser throw an error from the extra semicolon this is much less important than I first thought.

Thanks,

David

**Comment by DJMcNab** [comment] 2018-06-01 18:36
OK. I'm still surprised an error wasn't thrown at some point though. I think that the `EXTRA_EXPORTED_RUNTIME_METHODS` should have had the value of `["UTF16ToString",";'stringToUTF16'"]` when parsed.

I think that `;'stringToUTF16'` not existing should then have thrown an error somewhere further, but this seems to be a bug elsewhere in the handling of `EXTRA_EXPORTED_RUNTIME_METHODS`.
Again, I have no experience compiling C/C++ programs, so someone else would have to create a minimal reproduction. It could even be as simple as something like `emcc -s EXTRA_EXPORTED_RUNTIME_METHODS=[doesntexist]`, but I'm not sure.

**Comment by Auron52** [comment] 2018-06-01 19:23
emcc checking EXTRA_EXPORTED_RUNTIME_METHODS for existence and throwing an error would indeed be ideal in my opinion. Currently it will accept anything you pass and silently ignore them.
Do you have any thoughts on this @kripken?
Thanks,
David

**Comment by kripken** [comment] 2018-06-06 18:22
Hmm, we seem to already warn for this:
```
./emcc tests/hello_world.c -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["foo"]'
warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: foo
```
@Auron52 @DJMcNab Do you not see that warning?

**Comment by Auron52** [comment] 2018-06-08 00:18
I don't see the warning. However, by removing the optimization flag I am able to get it to show up.
For example:
emcc -s EXTRA_EXPORTED_RUNTIME_METHODS=['meowsa'] libanimal_library.so -s WASM=1 -o MyOutput.js
Output ":warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: meowsa"


emcc -s EXTRA_EXPORTED_RUNTIME_METHODS=['meowsa'] -Oz libanimal_library.so -s WASM=1 -o MyOutput.js
Output ""

Is there a known reason why this would occur?
Thanks,
David

**Comment by kripken** [comment] 2018-06-12 00:27
Thanks @Auron52 - looks like when optimizations are on, we disable assertions, and that check is only done when assertions are on. That seems wrong, I think we should fix it so it's always shown.

**Comment by rla** [comment] 2018-08-04 12:46
emcc.py function parse_string_list_members also cannot handle space (including newline) after last item and closing `]`, it causes warning to be emitted for the last quoted item, such as:

```
warning: invalid item (maybe a typo?) in EXPORTED_RUNTIME_METHODS: ccall"
```

The list in file could be formatted to have the closing `]` on the last line of the file for better readability.

**Comment by DJMcNab** [comment] 2018-08-12 10:31
Sorry again! Small typo, I think that https://github.com/kripken/emscripten/blob/e1d6f0dc3440e91cbf5d33ef982a38e0a091aba3/emcc.py#L3012 should be `result.append(current.rstrip()[1:-1])` to fix this.

**Comment by kripken** [comment] 2018-09-11 22:59
Should be fixed by that PR.

**Closed by kripken** 2018-09-11 22:59 UTC
Labels: help wanted
