### ISSUE TITLE
event.preventDeafult()  breaks HTML5 range input control

### ISSUE THREAD

**Issue by bruce-ba3** [kripken/emscripten#3926] opened 2015-11-19 11:06 UTC
Occurs in FireFox latest and Chrome latest. (Haven't tested in other browsers yet)

* FireFox: mouse up seems to move the slider to a random place
* Chrome: the range control seems to "capture" the mouse making a page unusable

Repro:
* emscripten portable SDK 1.35.0
* Put this on a web page that uses emscripten:

`<input id="slider2" type ="range" min ="100" max="500" step ="50" value ="100"/>`

* Open the page and try moving the slider. 

Here is a page that repros the issue as well:
http://builds.ba3.us/v2.0.ut.798.g644b9e6/Web/AltusMappingEngine/documentation/LightingSystemDemo.html

I believe the issues is in one of the 17 or so e.preventDefaults() library_html5.js. I commented them all out and it seemed to allow the slider to work properly, but I'm having some trouble narrowing it down.

**Comment by juj** [comment] 2015-11-19 14:10
Are you referring to these constructs: https://github.com/kripken/emscripten/blob/master/src/library_html5.js#L194 ?

    var shouldCancel = Runtime.dynCall('iiii', callbackfunc, 
    if (shouldCancel) {
        e.preventDefault();
    }

if so, then you're in control of the `preventDefault()` behavior since the value of `shouldCancel` comes from the return value from your HTML5 event callback function. See the documentation here: http://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#callback-functions .

**Comment by bruce-ba3** [comment] 2015-11-19 20:36
We don't have any callbacks that I'm aware of that would affect mouse operations.

**Comment by juj** [comment] 2015-11-20 12:35
Then it sounds like it is in one of the libraries you use? You said that commenting them out avoids the issue, so something in your application is then leading to calling those. Try doing an unminified build and add `console.log(new Error().stack);` where the `e.preventDefault();` are called to print a call stack of when that occurs, and trace the call stack down to the library that is causing it.

In either case, the code pointed to in `src/library_html5.js` works as intended, so closing this. If it turns out to be SDL/SDL2/something else, please open a new bug against the respective code in question.

**Closed by juj** 2015-11-20 12:35 UTC
Labels: HTML5 API

**Comment by zhanghaowx** [comment] 2016-08-11 03:47
I ran into exact the same problem recently. @bruce-ba3 How you finally solve it?

**Comment by bruce-ba3** [comment] 2017-02-13 21:22
I used jquery sliders.

**Comment by kichikuou** [comment] 2017-03-11 10:54
This is because SDL2 registers a mouseup handler that returns true (shouldCancel).
Filed emscripten-ports/SDL2#41.
