### ISSUE TITLE
Memory access out of bounds error when using _malloc on WASM compiled code

### ISSUE THREAD

**Issue by gordyr** [kripken/emscripten#5161] opened 2017-04-25 23:23 UTC
I have successfully compiled ```stb_dxt```, a DXT texture compressor written in C++, to emscripten and ```asm.js```.  This works wonderfully in Firefox but performance in Chrome is poor.  I am therefore attempting to compile the same program to ```WebAssembly``` using the following flags:

```emcc -O3 stb_dxt.cpp -o dxt.js -s DISABLE_EXCEPTION_CATCHING=1 -s NO_FILESYSTEM=1 -s EXPORTED_FUNCTIONS="['_rygCompress']" -s WASM=1 -s ALLOW_MEMORY_GROWTH=1```

My Javascript glue code, which works perfectly with ```asm.js```, needs to pass in an image ```ArrayBuffer``` like so:

```
    this.width = input.width;
    this.height = input.height;
    this.srcSize = input.data.length*input.data.BYTES_PER_ELEMENT;
    this.inputPtr = STB.Module._malloc(this.srcSize);
    this.outputPtr = STB.Module._malloc(Math.max(8, this.srcSize/8));

    this.inputHeap = new Uint8Array(STB.Module.HEAPU8.buffer, this.inputPtr, this.srcSize);
    this.outputHeap = new Uint8Array(STB.Module.HEAPU8.buffer, this.outputPtr, Math.max(8, this.srcSize/8));

    //set inputHeap to jpeg decoded RGBA data
    this.inputHeap.set(input.data);
```
As you can see I am using ```_malloc``` to allocate the memory for the passed in ```ArrayBuffer``` and also for what will be the resulting output ```ArrayBuffer``` once the program has run and compressed the texture to DXT1.

However, as soon as the first call to ```_malloc``` fires, I am getting an out of bounds memory error:

```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at <WASM UNNAMED> (<WASM>[24]+7062)
    at Object.Module._malloc
```

I assume that I'm doing something wrong, any help would be greatly appreciated.

The code I am trying to compile is available here: https://github.com/nothings/stb/blob/master/stb_dxt.h

**Comment by kripken** [comment] 2017-04-25 23:42
My first guess is that wasm startup is async, and perhaps you're calling into compiled code too early? Building with `-s ASSERTIONS=1 -s SAFE_HEAP=1` might find something.

(Otherwise, all those options and that code should work identically on asm.js and wasm, nothing seems wrong there.)

**Comment by kripken** [comment] 2017-04-25 23:42
Also worth checking if `-s BINARYEN_ASYNC_COMPILATION=0` changes things.

**Comment by gordyr** [comment] 2017-04-25 23:48
Thanks for the quick response, it's nearly 1am here.  I'll give your suggestions a try in the morning and let you know how I get on.

**Comment by gordyr** [comment] 2017-04-26 06:44
@kripken - I've tried compiling with the flags you suggested and I now get a serious of memory enlargement related errors:

```
Module.reallocBuffer: Attempted to grow from 16777216 bytes to 134217728 bytes, but got error: RangeError: WebAssembly.Memory.grow(): maximum memory size exceeded
```

```
Failed to grow the heap from 16777216 bytes to 134217728 bytes, not enough memory!
```

```
failed to set errno from JS
```

```
wasm-00010efe-24:3754 Uncaught (in promise) RuntimeError: memory access out of bounds
    at <WASM UNNAMED> (<WASM>[24]+7062)
```

I forgot to mentioned previously, but once I have compiled and the program and first run it, I get the following error:

```
WebAssembly Instantiation: memory import 10 has no maximum limit, expected at most 4294967295
```

It would appear that WebAssembly has recently changed their instantiation method to require the previously optional "maximum" option to be present. 

Therefore, I am manually adding this option into the resulting javascript file following compilation:

```
Module["wasmMemory"]=new WebAssembly.Memory({"initial":TOTAL_MEMORY/WASM_PAGE_SIZE, "maximum" : 256});
```

Perhaps this has something to do with it?   However, my understanding was this that was only for the WebAssembly instantiation, and was not in any way related to the amount of memory that a compiled program can use, which should be grown internally as it runs.

Perhaps there have been some breaking changes recently?

**Comment by gordyr** [comment] 2017-04-26 12:27
Interestingly, if I divide the amount of memory I am trying to allocate by WebAssembly's page size, the call to ```_malloc``` works:

  ```
 var WASM_PAGE_SIZE = 65536;
  this.srcSize = input.data.length * input.data.BYTES_PER_ELEMENT / WASM_PAGE_SIZE ;
  this.inputPtr = STB.Module._malloc(this.srcSize);
```

But then of course, when I then create the ```Uint8Array()``` view and try to set the data, the buffer isn't large enough.

Why should the ```_malloc``` call fail when I pass in the true length of the input data in bytes?

**Comment by gordyr** [comment] 2017-04-26 18:28
I've managed to fix my issue by doing the following:

1. Compiling with ```-s TOTAL_MEMORY=512MB```
2. Manually editing the javascript as follows:

```
Module["wasmMemory"]=new WebAssembly.Memory({"initial":TOTAL_MEMORY/WASM_PAGE_SIZE, "maximum" : TOTAL_MEMORY/WASM_PAGE_SIZE});
```

Everything then works, but sadly performance is far worse then ```asm.js```.

- In Firefox nightly running my program goes from 450ms in asm.js, to around 3,500ms.
- In Chrome Canary, is goes from 1500ms to 3,800ms.

Is there anything I can do to improve this?  Or is it simply down to the fact that WebAssembly isn't optimized to the level of asm.js yet?

**Comment by kripken** [comment] 2017-05-01 22:09
The `BINARYEN_MEM_MAX` option might help those build issues. Although things should work without it too, so something's gone wrong, but I don't remember all the details here to know what offhand - this went through a few revisions.

About perf, that is very surprising. It's just the wasm flag changed between those? Can you put up links to asm.js and wasm versions, built with `--profiling`, so we can reproduce? If it does reproduce, we should file bugs on browsers, although if it makes both of those browsers slower, perhaps it's our fault in the toolchain somehow.

**Comment by GordoRank** [comment] 2017-05-02 08:04
@kripken - After a few hours of profiling and tweaking I have been able to improve on performance to the point where the WASM version is now significantly faster then the asm.js one, in Chrome.  (Firefox is still slightly faster when using asm.js.  It seems that setting the input buffer in Chrome was causing a huge bottleneck.  Switching to ```Uint32Array``` views over the input ```ArrayBuffer``` solved it.

So this is great news, but still, I have to manually edit and include a ```maximum``` property in the javascript that's output by Emscripten.

**Comment by juj** [comment] 2017-05-02 13:30
> It would appear that WebAssembly has recently changed their instantiation method to require the previously optional "maximum" option to be present.

Do you have more info about this? I believe maximum should still be optional?

**Comment by gordyr** [comment] 2017-05-02 13:42
> Do you have more info about this? I believe maximum should still be optional?

The only info I can give you, is that without the ```maximum``` option being explicitly stated, compilation fails giving a ```memory import 10 has no maximum limit``` error.  The second I provide the option, the error goes away and everything works.

This is using the latest incoming build of Emscripten... Sorry I can't be any more help.

**Comment by kripken** [comment] 2017-05-02 16:45
Very strange. We need a full testcase to diagnose this, I think, I'm not sure where things are going wrong.

**Comment by evanw** [comment] 2017-06-08 18:01
We're also experiencing rare errors like this sometimes at Figma, but only in Chrome (not Firefox). I logged [a bug with Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=729768) before I found this issue.

**Comment by evanw** [comment] 2017-06-09 00:40
I finally got SAFE_HEAP working. I verified that SAFE_HEAP works by making sure `*(char*)0x3FFFFFFF` triggers the heap checks (in both Firefox and Chrome). I then ran Figma with SAFE_HEAP enabled and no heap checks were triggered (in both Firefox and Chrome) but Firefox loaded fine and Chrome threw "memory access out of bounds". Does this mean the bug is in Chrome and not in emscripten? Is there anything else I should try?

**Comment by kripken** [comment] 2017-06-09 00:44
I'm pretty sure it's a Chrome bug at this point, yeah. One last thing I'd try is to build with `-s DETERMINISTIC=1` which removes timing and randomness out of the picture. Also can't hurt to add `ASSERTIONS`.

**Comment by evanw** [comment] 2017-06-09 01:03
ASSERTIONS was a good idea. It looks like this is the problem:

```
Module.reallocBuffer: Attempted to grow from 1073741824 bytes to 1342177280 bytes, but got error: RangeError: WebAssembly.Memory.grow(): maximum memory size exceeded
```

Firefox allows the memory to grow over 1gb while Chrome doesn't. Figma sometimes needs more than 1gb of memory for large documents. Is the 1gb limit something that emscripten sets? Or is this a limitation of Chrome's implementation in particular?

**Comment by evanw** [comment] 2017-06-09 01:16
I saw your comment above about `BINARYEN_MEM_MAX` so I tried `-s BINARYEN_MEM_MAX=2147418112` but Chrome still fails to grow to 1342177280.

**Comment by kripken** [comment] 2017-06-09 01:25
Interesting. Looks like a chrome bug, emscripten doesn't set a 1GB limit (and it wouldn't be browser-specific in any case). Let's maybe move the discussion back to the chromium bug tracker to make sure they see it.

**Comment by evanw** [comment] 2017-06-09 18:31
Agreed. I posted a new comment to [the Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=729768#c8).

**Comment by kripken** [comment] 2017-06-09 18:38
Another thought here (not relevant to the Chrome side, so not posting in the bug there): in Chrome the allocation failed, so your app should have seen malloc/new return NULL. Does that happen properly for you, or is emscripten messing that up somehow?

**Comment by kripken** [comment] 2017-06-09 18:39
(That's assuming you have `ABORTING_MALLOC` turned off, which I think is the case? Otherwise it should have called abort and halted the app.)

**Comment by evanw** [comment] 2017-06-09 21:07
The crash is actually in malloc, not in our code. The call to malloc is still executing (i.e. at the top of the call stack) when the crash occurs so it never has the chance to return null. Here's what the stack trace looks like:

```
Uncaught RuntimeError: memory access out of bounds
    at <WASM UNNAMED> (<WASM>[331 (_malloc)]+4483)
    at <WASM UNNAMED> (<WASM>[703 (_malloca)]+138)
    at <WASM UNNAMED> (<WASM>[714 (operator new(unsigned int))]+9)
    at <WASM UNNAMED> (<WASM>[6072 (Codec::encodePhaseAndPropertyChanges(MultiplayerMessage const&, Fig::Message&))]+772)
    at <WASM UNNAMED> (<WASM>[6070 (Codec::toBuffer(MultiplayerMessage const&, MessageFormat))]+1135)
    at <WASM UNNAMED> (<WASM>[6069 (MultiplayerMessage::toBuffer(ImageMode, MessageFormat) const)]+197)
    ...
```

For what it's worth, I did verify that we aren't get any calls to malloc returning NULL before the crash.

**Comment by evanw** [comment] 2017-06-09 21:12
I think I've figured it out. We `#define MALLOC_ALIGNMENT 16` before dlmalloc.cpp. This is supposed to be safe:

```
MALLOC_ALIGNMENT         default: (size_t)(2 * sizeof(void *))
Controls the minimum alignment for malloc'ed chunks.  It must be a
power of two and at least 8, even on machines for which smaller
alignments would suffice. It may be defined as larger than this
though. Note however that code and data structures are optimized for
the case of 8-byte alignment.
```

Calling malloc crashes in Chrome if we `#define MALLOC_ALIGNMENT 16` but doesn't crash if we `#define MALLOC_ALIGNMENT 8` (the default). Any idea why this might be?

**Comment by evanw** [comment] 2017-06-09 21:20
Scratch that, never mind. That just lets us load the app in barely under 1gb. We still have the same problem if I make the document slightly bigger.

**Comment by kripken** [comment] 2017-06-11 04:02
Yeah, that crashing in malloc is definitely a sign of a problem in emscripten. I debugged it and found the issues, fixes and details in #5289.

**Comment by kripken** [comment] 2017-06-14 21:33
Should be fixed by that merged PR.

**Closed by kripken** 2017-06-14 21:33 UTC

**Comment by Y0QIN** [comment] 2018-10-28 07:36
I'm also experiencing this error when my program runs for a few minutes in Chrome
Uncaught RuntimeError: memory access out of bounds
    at wasm-function[79]:46
    at wasm-function[401]:379
    at wasm-function[992]:1112
    at wasm-function[338]:533
    at wasm-function[1253]:704
    at wasm-function[748]:707
    at wasm-function[1378]:245
    at wasm-function[1348]:205
    at wasm-function[1356]:9

**Comment by kripken** [comment] 2018-10-28 16:09
@Y0QIN - that might be a different issue, as I think the one here was fixed. To debug it, I'd start with building with `-g` so that stack trace is readable, and then hopefully what's going wrong can be figured out. If not, if you can share a testcase we can debug that here.
