### ISSUE TITLE
[1.37.13] AssertionError: Failed to run llvm optimizations:

### ISSUE THREAD

**Issue by abhisuri97** [kripken/emscripten#5305] opened 2017-06-14 04:54 UTC
I am getting the following error running emcc:
```
$ emcc libbayes_net_ex.a -o out.js


INFO:root:generating system library: libc.bc... (this will be cached in "/Users/abhi/.emscripten_cache/asmjs/libc.bc" for subsequent builds)
INFO:root: - ok
INFO:root:generating system library: dlmalloc.bc... (this will be cached in "/Users/abhi/.emscripten_cache/asmjs/dlmalloc.bc" for subsequent builds)
INFO:root: - ok
/Users/abhi/Downloads/emsdk-portable/clang/e1.37.13_64bit/opt: error loading file '/private/var/folders/8x/d4z0ynkd0z37z1jy6x8b0sdw0000gn/T/emscripten_temp_shjQr6_archive_contents/bayes_net_ex.cpp.o'
Traceback (most recent call last):
  File "/Users/abhi/Downloads/emsdk-portable/emscripten/1.37.13/emcc", line 13, in <module>
    emcc.run()
  File "/Users/abhi/Downloads/emsdk-portable/emscripten/1.37.13/emcc.py", line 1494, in run
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "/Users/abhi/Downloads/emsdk-portable/emscripten/1.37.13/tools/shared.py", line 1838, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
```

The file in question is in the following zip file. just run `emcc libbayes_net_ex.a -o out.js` after extracting
[libbayes_net_ex.a.zip](https://github.com/kripken/emscripten/files/1073531/libbayes_net_ex.a.zip)

With regard to what may be causing the issue, I am not exactly sure since I don't have much experience with compilers. I am trying to compile files from dlib if that helps at all.

**Comment by juj** [comment] 2017-06-14 14:50
Examining the archive file:

```
C:\Users\clb\Downloads\libbayes_net_ex.a>llvm-ar xo libbayes_net_ex.a

C:\Users\clb\Downloads\libbayes_net_ex.a>llvm-objdump -private-header bayes_net_ex.cpp.o

bayes_net_ex.cpp.o:     file format Mach-O 64-bit x86-64

Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00      OBJECT     5       1008 SUBSECTIONS_VIA_SYMBOLS
```

suggests that the object in that file is native compiled code, and not one that was produced with Emscripten.

However I think we should improve the error message here to guide people to understand the scenario.

**Comment by juj** [comment] 2017-06-15 09:57
The improved error message was merged, I'll close this as resolved. However if the root cause ends up being something else and it looks like there's still something to do on Emscripten side, feel free to reopen!

**Closed by juj** 2017-06-15 09:57 UTC
