### ISSUE TITLE
locateFile is called on data: URI for memory initializer in 1.37.25 with --memory-init-file 0

### ISSUE THREAD

**Issue by brion** [kripken/emscripten#5952] opened 2017-12-19 22:57 UTC
Regression from 1.37.22 to 1.37.25: when using `--memory-init-file 0`, the memory initializer segment is now stored in a data URI string instead of a raw array, and it's read using XHR in the same was as an external file would have.

However before being loaded, the data: URI is passed through the Module's `locateFile` function if present -- this can be used to prepend a path prefix for instance, which in this case fails because it's not a relative path, but a separate data URI.

Workaround:
* check for 'data:' prefix in the locateFile function and don't prepend path in this case

**Comment by brion** [comment] 2017-12-19 23:18
(this may just be a doc issue)

**Comment by juj** [comment] 2017-12-20 17:33
Ouch, hmm... The intent was never for `Module.locateFile` to get called with a direct data URI string, I think we should be considering this a bug. This sounds like it's probably related to the `SINGLE_FILE` PR.

It is possible we could expand the spec and intent of the `Module.locateFile` function as suggested, but not sure if there's much use for that, and breaking existing code is annoying.

**Comment by kripken** [comment] 2017-12-20 20:47
Yeah, this is a regression from `SINGLE_FILE`, cc @buu700 

We should fix and add a test, since this isn't currently covered in the test suite.

**Comment by buu700** [comment] 2017-12-20 20:51
Sorry about that! I'll look into this today.

**Comment by kripken** [comment] 2017-12-21 16:09
Fixed by that PR.

**Closed by kripken** 2017-12-21 16:09 UTC

**Comment by aggregate1166877** [comment] 2023-06-21 11:42
> It is possible we could expand the spec and intent of the `Module.locateFile` function as suggested, but not sure if there's much use for that, and breaking existing code is annoying.

I currently have a use-case for this. I have 2 wasm bins that need to be retrieved; one is 25MB (ffmpeg), and the other is 5MB (mediainfo). Together, they give me a coherent video editor. Downloading 30MB each page load (excluding my bundle) seems rather excessive. It makes sense to me to store these bins somewhere, maybe IndexedDB, and then just feed the cached DB entry  (a data URI in this case) into `Module.locateFile`.

Note that I'm somewhat new to wasm modules; it's possible there's another way of passing in stored binaries without contacting the internet that I'm not aware of. Please correct me if that's the case.
