### ISSUE TITLE
Installer v1.29 installs folder 1.30/emcc -v also reports version 1.30. Installer adds v1.29.0 in PATH environment variable.

### ISSUE THREAD

**Issue by CainitePrince** [kripken/emscripten#3449] opened 2015-05-11 11:33 UTC
After installing using the windows installer (https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-1.29.0-web-64bit.exe). I tried to verify the installation with emcc -v. This did not work. Windows did not recognize the command.

Then I tried the same thing using the Emscripten command prompt. This gave me an error. Some error message having to do with PATH. I thought the path must be not set properly. When I tried to print the path environment variable it was gone. I tried SET and echo %path%.

Then I tried viewing the environment variables using the windows GUI. This give an error stating %windir%\System32\systemadvancedproperties.exe could not be found. %windir% was also gone.

Rebooting my system thankfully solved the missing environments variables.

Calling 'python emsdk construct_env' (from inside the folder) worked fine. Calling emcc.bat -v (from Program Files\Emscripten\emscripten\1.30.0) also worked fine.

Then I looked at the environment variables. The installer had successfully added the emscripten paths. However it added C:\Program Files\Emscripten\Emscripten\1.29.0. The files were installed in the 1.30.0 folder. I renamed the 1.30.0 folder to 1.29.0 and now everything seems to work fine.

**Comment by juj** [comment] 2015-05-11 12:12
This is a duplicate of https://github.com/juj/emsdk/issues/17 . The web installer should probably be renamed to "web-latest", since the web installer will always install the latest version. No reason though why that should be, but let's continue the discussion in the other github issue.

It is best to use the full installer of one needs to install an older version, or use the cmdline `emsdk` tool to install an older version.

**Closed by juj** 2015-05-11 12:12 UTC
