### ISSUE TITLE
failure to parse metadata

### ISSUE THREAD

**Issue by ssx71** [kripken/emscripten#5593] opened 2017-09-18 14:06 UTC
error occurs when inside a string there is a TAB

Error Output :

	ERROR:root:emscript: failure to parse metadata output from compiler backend. raw output is:

	{
	"staticBump": 1728,
	"declares": ["__syscall140", "pthread_self", "pthread_cleanup_push", "__syscall146", "pthread_cleanup_pop", "__syscall6", "__syscall54", "__lock", "__unlock", "abort", "sbrk", "emscripten_asm_const_int"],"redirects": {},"externs": [],"implementedFunctions": ["_main", "___stdio_close", "___stdio_write", "___stdio_seek", "___syscall_ret", "___errno_location", "_cleanup_522", "___unlockfile", "___stdout_write", "___lockfile", "_fflush", "___fflush_unlocked", "_malloc", "_free"],"tables": {  "ii": "var FUNCTION_TABLE_ii = [0,___stdio_close];",
	  "iiii": "var FUNCTION_TABLE_iiii = [0,0,___stdout_write,___stdio_seek,0,___stdio_write,0,0];",
	  "vi": "var FUNCTION_TABLE_vi = [0,0,0,0,_cleanup_522,0,0,0];"
	},"initializers": [],"exports": [],"aliases": {},"cantValidate": "","simd": 0,"simdUint8x16": 0,"simdInt8x16": 0,"simdUint16x8": 0,"simdInt16x8": 0,"simdUint32x4": 0,"simdInt32x4": 0,"simdFloat32x4": 0,"simdFloat64x2": 0,"simdBool8x16": 0,"simdBool16x8": 0,"simdBool32x4": 0,"simdBool64x2": 0,"maxGlobalAlign": 4,"namedGlobals": {},"asmConsts": {"0": ["{ var a=$0; error=\" \"; }", ["ii"]]}
	}

	Traceback (most recent call last):
	  File "C:\emscripten\emscripten\1.37.1\\emcc", line 13, in <module>
		emcc.run()
	  File "C:\emscripten\emscripten\1.37.1\emcc.py", line 1635, in run
		final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
	  File "C:\emscripten\emscripten\1.37.1\tools\shared.py", line 1745, in emscripten
		call_emscripten(cmdline)
	  File "C:\emscripten\emscripten\1.37.1\emscripten.py", line 1783, in _main
		temp_files.run_and_clean(lambda: main(
	  File "C:\emscripten\emscripten\1.37.1\tools\tempfiles.py", line 78, in run_and_clean
		return func()
	  File "C:\emscripten\emscripten\1.37.1\emscripten.py", line 1788, in <lambda>
		DEBUG=DEBUG,
	  File "C:\emscripten\emscripten\1.37.1\emscripten.py", line 1689, in main
		temp_files=temp_files, DEBUG=DEBUG)
	  File "C:\emscripten\emscripten\1.37.1\emscripten.py", line 91, in emscript
		funcs, metadata, mem_init = get_and_parse_backend(infile, settings, temp_files, DEBUG)
	  File "C:\emscripten\emscripten\1.37.1\emscripten.py", line 175, in get_and_parse_backend
		raise e
	ValueError: Invalid control character at: line 7 column 374 (char 1103)

File Example :

	#include <emscripten.h>
	 
	int main ( void )
	{

		int retVal=EM_ASM_INT(
		{
			var a=$0;
			
			error="	";
			
		}, 123  );
		 
	}

In variabile error i have put a TAB character, emscripten fail to output javascript file.

	emcc errore.cpp -o main.js

**Comment by juj** [comment] 2017-09-18 16:42
I can reproduce. It looks like someone decided that JSON data should not be allowed to contain tabs. My eyes roll wondering about why not...

**Comment by juj** [comment] 2017-09-18 16:44
Fix in above two commits.

**Comment by ssx71** [comment] 2017-09-18 19:16
this error also happens with : 

\'   \a and \v

**Comment by juj** [comment] 2017-09-22 09:16
Hmm, what are `\'`, `\a` and `\v` characters? I am not familiar with those control sequences.

Does it work if you pass `\\'`, `\\a` or `\\v`?

**Comment by ssx71** [comment] 2017-09-22 18:39
Nowadays I think they are no longer used, perhaps in some old RS232 terminal.
However if you put this escapes sequences in a string, fastcomp fail to compile;
As you can verify in this below example :

	#include <emscripten.h>

	// \v ko , \\v ok
	// \' ko , \\' ok
	// \F ko

	int main ( void )
	{
	 EM_ASM(
		console.log ("\v");
	 );
	 return 0 ;
	}

Compiler do not exactly recognize invalid escape, below is the error that fastcomp generates :

	ValueError: Invalid \escape: line 7 column 369 (char 1094).
	
These escape sequences  works with double backslash \\ ( \\v ) ; 
as can be seen in the remarks (//) of the source.

**Comment by juj** [comment] 2017-10-12 18:22
Gotcha. I think we do not want to support such odd escape sequences, since like you mention, these are not used these days, and they are more possibly a signal of a typo. Let me close this bug as resolved, since the important part with the tab characters works now. Thanks for reporting!

**Closed by juj** 2017-10-12 18:22 UTC
