### ISSUE TITLE
uglify-js not checked in to emscripten

### ISSUE THREAD

**Issue by nedres** [kripken/emscripten#7427] opened 2018-11-01 13:24 UTC
Hi,

We're facing an issue where our CI environment is loaded from git, and uglify-js is unavailable because node_modules is in `.gitignore`.  This is on version 1.38.11.

Should node-modules be bundled in, or is there a recommended fix or workaround?

**Comment by kripken** [comment] 2018-11-01 16:54
Where do you need `uglify-js`? Emscripten bundles the uglify parser internally for the JS optimizer, do you mean something has gone wrong with that, or do you need uglify for some other reason and emscripten's gitignore is blocking it?

**Comment by nedres** [comment] 2018-11-01 17:14
Thanks for the quick response!  Yes, we need it for the JS optimizer. The typical error looks like:
```
18>module.js:538
    throw err;
    ^

Error: Cannot find module '../tools/eliminator/node_modules/uglify-js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\dev\3rdparty\Emscripten\emscripten\1.38.11\tools\js-optimizer.js:132:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by missmah** [comment] 2018-11-02 04:36
These appear to be happening in our `Debug` build (at least - unsure whether it's all builds)

```
tools.shared.Py2CalledProcessError: Command '['C:/dev/3rdparty/Emscripten/node/8.9.1_64bit/bin/node.exe', 'C:\\dev\\3rdparty\\Emscripten\\emscripten\\1.38.11\\tools\\js-optimizer.js', 'C:\\dev\\Build\\Output\\TEMP\\tmpgexsj0.jsfunc_0.js', 'noPrintMetadata', '--debug', 'asm', 'safeHeap', 'last']' returned non-zero exit status 1
```

Judging by this, I suspect possibly it's our usage of `SAFE_HEAP=1`

`.CompilerDebugOptimizations = .FullDebug + .TestBuild`

Where:
```
.FullDebug = ' -O0 -s SAFE_HEAP=1 -g4'
.TestBuild = ' -s STACK_OVERFLOW_CHECK=2 -s SAFE_HEAP=1 -s ASSERTIONS=2 -s ALIASING_FUNCTION_POINTERS=0 -s WARN_UNALIGNED=1 -s SAFE_HEAP_LOG=1 --tracing --profiling --profiling-funcs'
```

It worries me that we have `-s SAFE_HEAP=1` twice by combining those two, though I assume/hope that should be safe even if inelegant.

The command will of course have `emcc -o` and whatnot. I think we're using `asm.js` here and not `wasm` -- if you need, @nedres can probably get you the actual full command line tomorrow.

**Comment by missmah** [comment] 2018-11-02 04:46
I just took a deeper look, and of course there's a *lot* of additional arguments missing from the picture I just gave you (but the pieces I mentioned *are* included in the command line). The full command line @nedres gets you tomorrow will be quite long :-)

**Comment by nedres** [comment] 2018-11-02 12:13
Here's an example:
`D:\dev\3rdparty\Emscripten\python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe D:/dev/3rdparty/Emscripten/emscripten/1.38.11/emcc -o "D:\dev\Build\Output\HTML5-Debug\MicroAudioAPI\MicroAudioAPI_ExampleApp\MicroAudioAPI_ExampleApp.html" "D:\dev\Build\Output\HTML5-Debug\MicroAudioAPI\MicroAudioAPI_ExampleApp\Unity1.o"   --em-config "C:\Users\ned\.emscripten" --cache "D:/dev/Build/Output\.emscripten_cache" --use-preload-plugins -s WASM=0 --llvm-lto 0 -O0 -s SAFE_HEAP=1 -g4`

**Comment by nedres** [comment] 2018-11-02 12:18
The issue occurs across all builds; here's an example with release settings:
`D:\dev\3rdparty\Emscripten\python\2.7.13.1_64bit\python-2.7.13.amd64\python.exe D:/dev/3rdparty/Emscripten/emscripten/1.38.11/emcc -o "D:\dev\Build\Output\HTML5-Shipping\MicroAudioAPI\MicroAudioAPI\MicroAudioAPI.js" "D:\dev\Build\Output\HTML5-Shipping\MicroAudioAPI\MicroAudioAPI\Unity1.o"   --em-config "C:\Users\ned\.emscripten" --cache "D:/dev/Build/Output\.emscripten_cache" --use-preload-plugins -s WASM=0 --llvm-lto 3 D:/dev/3rdparty/fmod/html5/api/lowlevel/lib/fmod.bc -s SIDE_MODULE=1 -s OUTLINING_LIMIT=50000`

**Comment by kripken** [comment] 2018-11-02 16:01
I don't see anything obviously wrong there. Do the files actually exist at `../tools/eliminator/node_modules/uglify-js` where it is looking for them - maybe your checkout has some files removed?

Might be worth trying a simpler command first, just `./emcc tests/hello_world.c` in the emscripten directory, to see that that finds uglify properly.

Otherwise, please try to create a testcase I can reproduce the problem with and debug.

**Comment by nedres** [comment] 2018-11-02 17:09
Sorry if I wasn't clear before.  These commands succeed normally on machines that used `emsdk` to install emscripten. Our CI machines, however, get their emscripten installation from our git repo-- but the git repo doesn't have `node_modules`, because it's been filtered out.

My question is: why is `node_modules` filtered out, if `uglify` is going to get called?

**Comment by kripken** [comment] 2018-11-02 18:30
It should work ok from the git repo (that's how our CI works, and how I always work locally) - uglify is actually checked into the build directly, at

https://github.com/kripken/emscripten/tree/incoming/tools/eliminator/node_modules/uglify-js

Note that that contains `node_modules` in a subdirectory, so it's not affected by the gitignore file.

**Comment by missmah** [comment] 2018-11-02 18:31
To be clear, @nedres means it's been filtered out by `Emscripten`'s `.gitignore`

For us, that file is located at: `D:\dev\3rdparty\Emscripten\emscripten\1.38.11\.gitignore`

And the contents look like this:

```
# vim/emacs temporary/backup files
*~
*.swp

*.diff
*.pyc
*.bc

node_modules/

# Ignore generated files

tests/fake/
tests/freetype/objs/*.o
tests/freetype/objs/*.lo

third_party/lzma.js/lzip/*.o
third_party/lzma.js/lzma-native
third_party/lzma.js/lzma-native.exe

tools/optimizer_build/
```

The ask is why is `node_modules/` in `.gitignore` if it's supposed to be available to `Emscipten` and `Emscipten` is meant to be able to be in source control?

**Comment by kripken** [comment] 2018-11-02 18:35
Thanks, I think I see things more clearly now. Our last 2 comments sort of collided, but see my last one - I don't think that gitignore is the issue, as it's ignoring the top level `node_modules`, while uglify is present under `tools/`.

Based on the error message you get, I'd guess either that `tools/` subdir is not present on your system somehow, or you are calling emcc in a way that hits a bug when it looks for it - I see a relative path there, `../`, so maybe your current directly affects this somehow, or the `.emscripten` config file has an incorrect path?

**Comment by missmah** [comment] 2018-11-02 18:38
Indeed, we did seem to collide there! :-) Thanks for the quick response!

Looking into this, you appear to be right!

And looking at our `emscripten/1.38.11/tools/`, there is no `eliminator` folder at all:
![image](https://user-images.githubusercontent.com/10825214/47934055-a93eb380-deac-11e8-9731-3d52a5125193.png)

I do not know why this is - but this seems to be the true root-cause...

@nedres Any idea why we would be missing these entire folders? This feels like a mistake was made the last time the `Emscripten` update was committed into `git`?

**Comment by missmah** [comment] 2018-11-02 19:26
An update. Our git and your git seem to interpret `node_modules/` differently.

I just updated to `Git 2.19.1` and `Git LFS 2.6.0` to be sure it wasn't a bug in our e.g. older version of git. Same behavior.

I'm not sure why our respective git(s) are interpreting this differently. My intuition would be that yours is interpreting it correctly; but, maybe not...

For our `git`, having `node_modules/` in `.gitignore` covers *all* `node_modules/` anywhere in the downstream path.

Your git appears to treat it as equivalent to `./node_modules/`

If we change the `.gitignore` to explicitly say `./node_modules/`, then we get the intended behavior where both `tools/eliminator` and `tools/node_modules` appear as files tracked by `git`.

Interestingly, this also explains why we've always had to do `npm install source-map`! And, if you guys are using a custom version of `source-map` like you are for `uglify-js`, it might mean we would have had subtle incompatibilities.

So, it feels like the right answer might be to change emscripten's `.gitignore` to say `./node_modules/` - or, possibly `!tools/eliminator` and `!tools/node_modules/`, but I think `!` is a bit more dangerous, and it would be nice to stick with a positive rule, rather than a negative rule.

Maybe you can give us some better insight into the problem - it would be great to know why our git(s) appear to be acting differently here!

**Comment by nedres** [comment] 2018-11-02 19:35
We also see this behaviour on Ubuntu with git 2.7.4.

**Comment by nedres** [comment] 2018-11-02 21:02
Still checking, but this may be a possibility:

Having `node_modules/` in `.gitignore` filters out `tools/eliminator/node_modules`, unless those files are already in git.

(for example, adding `A/` to `.gitignore` hides both `A/file1` and `B/A/file2`)

The `node_modules` line in `gitignore` is 5 years old (https://github.com/kripken/emscripten/blame/incoming/.gitignore)
..and the `uglify` files were added earlier (https://github.com/kripken/emscripten/tree/incoming/tools/eliminator/node_modules/uglify-js/lib)
..so in at least some cases, this issue could be masked.

We install with `emsdk`, then add the files to our 3rdparty repo in an `Emscripten/VersionNumber` folder.  The emscripten `gitignore` filters out *both* `node_modules` folders.

Possibly changing the `gitignore` line to `./node_modules` would fix this? Though I don't understand why you don't see the issue.

**Comment by kripken** [comment] 2018-11-02 21:17
That sounds plausible (does your CI setup create a new git repo, or copy files around? if so then the files being added after the .gitignore might explain things, while just using the current upstream repo works for everyone else).

If changing to `./node_modules` fixes it for you, that sounds like a good fix.

**Comment by missmah** [comment] 2018-11-02 21:21
Yeah, we manually create a repo for our internal company use with the updated emscripten, and adding files to this repo, it appears the eliminator files get excluded.

We do it this way so that we can easily update the whole company to different emscripten versions seamlessly with a single commit. Also, it lets us maintain consistent history of functional past emscripten versions along with our code history, so we can always go back and properly build old commits.

We can certainly make the `./node_modules/` change locally, but this also sounds like it might be a good thing to upstream (to prevent this from happening to anyone else who installs Emscripten into their own repo).

Should we send you a pull request?

**Closed** 2018-11-02 23:41 UTC
