### ISSUE TITLE
dynamic_cast issue when using dynamic linking

### ISSUE THREAD

**Issue by anlambert** [kripken/emscripten#3465] opened 2015-05-21 13:58 UTC
Hi,

I recently start playing with the new dynamic linking features in the incoming branch.
I am trying to port a C++ application that is extensible through plugins dynamically loaded.
Currently, all these plugins are statically linked in my emscripten build. In order to reduce
the generated javascript file size (and so the startup time), I wanted to try the new dynamic linking feature in order to load these plugins dynamically as needed.

I managed to compile each plugin as a javascript side module by following the instructions in the wiki.
Then I tried to load one of them dynamically with emscripten, which seemed to work fine as the dynamically loaded plugin was correctly registered in the plugins database of my application (got some warnings about duplicated symbols but it does not seem a critical issue).

However, the use of the dynamic_cast operator fails when used on a class hierarchy defined in the side module. Seems that an incorrect index for the FUNCTION_TABLE_viiiiii array is computed, resulting in a wrong function call.

I managed to create a sample program illustrating the issue. The code of the side module is given in side.* and the one from the main module in main.cpp.

side.h
```c++
#ifndef SIDE_H
#define SIDE_H

class Base {
    
public:
    
    virtual void printName();
    
};

class Derived : public Base {
    
public:
    
    void printName();
};

#endif
```
side.cpp
```c++
#include "side.h"

#include <iostream>

using namespace std;

void Base::printName() {
    cout << "Base" << endl;
}

void Derived::printName() {
    cout << "Derived" << endl;
}
```

main.cpp
```c++
#include "side.h"

#include <iostream>

using namespace std;

int main() {
    // force inclusion of iostream in main module
    cout << "starting main" << endl;
    
    // those calls work fine
    Base *base = new Base();
    Base *derived = new Derived();
    base->printName();
    derived->printName();
    
    // the call to dynamic_cast fails due to an invalid lookup in a function table 
    if (dynamic_cast<Derived*>(derived)) {
      cout << "OK" << endl;
    } else {
      cout << "KO" << endl;
    }
    
    return 0;
}
```
When compiling and executing that sample program, I got the following error and stack trace :

```
Invalid function pointer called with signature 'viiiiii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
main.js:138 Build with ASSERTIONS=2 for more info.
main.js:135 10
main.js:138 10
main.js:257980 Uncaught abort(10) at Error
    at jsStackTrace (http://localhost:8888/main.js:1240:13)
    at stackTrace (http://localhost:8888/main.js:1257:22)
    at abort (http://localhost:8888/main.js:258097:44)
    at nullFunc_viiiiii (http://localhost:8888/main.js:26709:474)
    at Array.b10 (http://localhost:8888/main.js:255044:96)
    at ftCall_viiiiii (http://localhost:8888/main.js:26892:35)
    at ___dynamic_cast (http://localhost:8888/main.js:63125:4)
    at _main (http://localhost:8888/main.js:28877:86)
    at Object.asm._main (http://localhost:8888/main.js:248377:19)
    at Object.callMain (http://localhost:8888/main.js:257963:30)
```
Calling dynamic_cast from the side module also fails.

I tried to investigate the cause of that issue, without success ... So I am reporting it here.

**Comment by kripken** [comment] 2015-05-21 19:40
Thanks for reporting! I can confirm this. Looks like a deep problem, investigating now.

**Comment by kripken** [comment] 2015-05-21 20:36
Fixed on incoming, we were missing constant offsets on relocated *external* symbols.

**Closed by kripken** 2015-05-21 20:36 UTC
