### ISSUE TITLE
code miscompiled at -Os and above on x86_64-unknown-linux-gnu 

### ISSUE THREAD

**Issue by zhendongsu** [kripken/emscripten#3520] opened 2015-06-08 04:57 UTC
The following code (small.c) seems to be miscompiled by emscripten at -Os and above: 

```
int a, b;

struct S
{
  volatile int f0;
  int f1;
}; 

volatile struct S c;
struct S d;

struct S
fn1 ()
{
  if (a)
    {
      a = 0;
      return d;
    }
  if (c.f1)
    d.f1 && c.f1;
  else
    d.f0;
  d.f0;
  return d;
}

int
main ()
{
  fn1 ();
  while (b)
    ;
  return 0;
}
```

$ emcc -v
emcc (Emscripten gcc/clang-like replacement) 1.33.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 2a66b5ffba63f1e36458d41fafc2874a1abf63fe) (https://github.com/kripken/emscripten-fastcomp/ e2939f6878307899c17d1a23f51ba3fe5afbe6af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.1.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.1.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
$ 
$ emcc -O1 small.c
$ node a.out.js
 
$ emcc -Os small.c
$ node a.out.js
/data2/c-hunter/test/javascript-nor/RES/check3/8/reduce/a.out.js:5
;B=a}function ua(){return B|0}function va(){if(!(c[2]|0)){if(c[7]|0)}else c[2]
                                                                    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
$

**Comment by kripken** [comment] 2015-06-08 18:22
I can't reproduce this on incoming (`1.33.1`) or on `1.33.0`. Does anything change if you do `emcc --clear-cache`?

**Comment by zhendongsu** [comment] 2015-06-08 18:34
No, I still get the same error: 

$ emcc --clear-cache
WARNING  root: clearing cache
INFO     root: (Emscripten: Running sanity checks)
$ 
$ emcc -Os small.c
$ node ./a.out.js
/data2/c-hunter/test/javascript-nor/RES/check3/8/reduce/a.out.js:5
;B=a}function ua(){return B|0}function va(){if(!(c[2]|0)){if(c[7]|0)}else c[2]
                                                                    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
$

**Comment by kripken** [comment] 2015-06-08 18:37
Do you still get the issue with `EMCC_DEBUG=2` in the env? if so, can you provide all the `emcc-*` temp files in `/tmp/emscripten_temp` after running that? (that will show all js optimizer passes separately).

**Comment by zhendongsu** [comment] 2015-06-08 18:56
With EMCC_DEBUG=2, the error disappears, but it still triggers with EMCC_DEBUG=1. 

$ EMCC_DEBUG=1 emcc -Os small.c
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python2"
DEBUG    root: JAVA not defined in ~/.emscripten, using "java"
WARNING  root: invocation: /home/su/software/emsdk_portable/emscripten/master/emcc -Os small.c  (in /data2/c-hunter/test/javascript-nor/RES/check3/8/reduce)
INFO     root: (Emscripten: Running sanity checks)
DEBUG    root: compiling to bitcode
DEBUG    root: emcc step "parse arguments and setup" took 0.00 seconds
DEBUG    root: compiling source file: small.c
DEBUG    root: running: /home/su/software/emsdk_portable/clang/fastcomp/build_master_64/bin/clang -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=33 -D__EMSCRIPTEN_tiny__=0 -Werror=implicit-function-declaration -nostdinc -Xclang -nobuiltininc -Xclang -nostdsysteminc -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/local/include -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include/compat -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include/emscripten -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include/libc -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/lib/libc/musl/arch/js -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include/libcxx -Os -mllvm -disable-llvm-optzns small.c -Xclang -isystem/home/su/software/emsdk_portable/emscripten/master/system/include/SDL -emit-llvm -c -o /tmp/tmpatxLMW/small_0.o
DEBUG    root: emcc step "bitcodeize inputs" took 0.03 seconds
DEBUG    root: optimizing small.c
DEBUG    root: emcc: LLVM opts: -Os -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false
DEBUG    root: emcc step "process inputs" took 0.04 seconds
DEBUG    root: will generate JavaScript
DEBUG    root: including libc.bc
DEBUG    root: emcc step "calculate system libraries" took 0.02 seconds
DEBUG    root: linking: ['/tmp/tmpatxLMW/small_0_1.o', '/home/su/.emscripten_cache/libc.bc']
DEBUG    root: emcc: llvm-linking: ['/tmp/tmpatxLMW/small_0_1.o', '/home/su/.emscripten_cache/libc.bc'] to /tmp/tmpatxLMW/a.out.bc
DEBUG    root: emcc step "link" took 0.08 seconds
DEBUG    root: saving intermediate processing steps to /tmp/emscripten_temp
DEBUG    root: emcc: LLVM opts: -strip-debug -internalize -internalize-public-api-list=main,malloc,free -globaldce -pnacl-abi-simplify-preopt -pnacl-abi-simplify-postopt -disable-loop-vectorization -disable-slp-vectorization -vectorize-loops=false -vectorize-slp=false -vectorize-slp-aggressive=false
DEBUG    root: emcc step "post-link" took 0.05 seconds
DEBUG    root: LLVM => JS
DEBUG    root: PYTHON not defined in ~/.emscripten, using "/usr/bin/python2"
DEBUG    root: JAVA not defined in ~/.emscripten, using "java"
DEBUG    root: emscript: llvm backend: /home/su/software/emsdk_portable/clang/fastcomp/build_master_64/bin/llc /tmp/tmpatxLMW/a.out.bc -march=js -filetype=asm -o /tmp/emscripten_temp/tmpzzWngX.4.js -O2
DEBUG    root:   emscript: llvm backend took 0.0630280971527 seconds
DEBUG    root: emscript: js compiler glue
DEBUG    root:   emscript: glue took 0.499302148819 seconds
DEBUG    root: asm text sizes[[104429, 1848], 0, 130, 1022, 0, 0, 32, 274, 268, 466, 350]
DEBUG    root:   emscript: final python processing took 0.00293898582458 seconds
DEBUG    root: emcc step "emscript (llvm=>js)" took 0.66 seconds
DEBUG    root: wrote memory initialization to a.out.js.mem
DEBUG    root: emcc step "source transforms" took 0.00 seconds
DEBUG    root: running js post-opts
DEBUG    root: applying js optimization passes: asm eliminate simplifyExpressions simplifyIfs registerizeHarder minifyNames cleanup asmLastOpts last minifyWhitespace
chunkification: num funcs: 15 actual num chunks: 1 chunk size range: 107477 - 107477
DEBUG    root: js optimizer using native
.
running cleanup on shell code
DEBUG    root: emcc step "js opts" took 0.98 seconds
DEBUG    root: emcc step "final emitting" took 0.00 seconds
DEBUG    root: total time: 1.86 seconds
$ 
$ node a.out.js
/data2/c-hunter/test/javascript-nor/RES/check3/8/reduce/a.out.js:5
;B=a}function ua(){return B|0}function va(){if(!(c[2]|0)){if(c[7]|0)}else c[2]
                                                                    ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
$

**Comment by kripken** [comment] 2015-06-08 20:44
The temp files in `EMCC_DEBUG=1` are not as good, but will still help, if you can provide those.

**Comment by zhendongsu** [comment] 2015-06-08 20:56
Sure, but I don't see how to attach the files for uploading.  Could you let me know how?

**Comment by kripken** [comment] 2015-06-08 20:59
github sadly doesn't have a good way. Can put them in a gist (just need the `.js` files), or on a dropbox public folder, or some other service.

**Comment by zhendongsu** [comment] 2015-06-08 21:05
I see.  Here it is: 
https://dl.dropboxusercontent.com/u/10788753/emcc-temp.zip

**Comment by kripken** [comment] 2015-06-09 00:19
Thank you, I can reproduce the problem using those.

**Comment by zhendongsu** [comment] 2015-06-09 00:24
Great; thank you for looking into the issue, Alon!

**Comment by kripken** [comment] 2015-06-09 01:02
Ok, this was a bug with the native minifier. We need to keep a `;` symbol after an if. Fixed on incoming.

**Closed by kripken** 2015-06-09 01:02 UTC
