### ISSUE TITLE
TypeError: asm.js type error: could not match typed array name

### ISSUE THREAD

**Issue by httpdigest** [kripken/emscripten#3794] opened 2015-09-19 17:43 UTC
I get this error on Firefox Nighty version "43.0a1 (2015-09-19)" on Windows 7 x64 when running a program compiled with `-s USE_PTHREADS=1` (regardless of optimization level O1 through O3).

The erroneous line is the line of the following snippet with the `global.I8Array`:
```JavaScript
// EMSCRIPTEN_START_ASM
var asm = (function(global, env, buffer) {
  'use asm';
  
  var HEAP8 = new global.I8Array(buffer);     <-- this line invokes the error
  var HEAP16 = new global.I16Array(buffer);
  var HEAP32 = new global.I32Array(buffer);
  var HEAPU8 = new global.U8Array(buffer);
  ...
```

The exact error line output by Firefox is:
`TypeError: asm.js type error: could not match typed array name jamvm.js:7306:18`

EDIT:
I also get this type error on Firefox with the pthread test `test_pthread_malloc.cpp` of Emscripten.

**Comment by kripken** [comment] 2015-09-19 18:13
Looks like a duplicate of #3719.

**Comment by httpdigest** [comment] 2015-09-20 10:06
You are right. Although I remember that SharedArrayBuffers did validate at some point in the past as asm.js. However, back then, the HEAP8 variable was explicitly set to a SharedInt8Array.

**Closed** 2015-09-20 13:03 UTC

**Comment by juj** [comment] 2015-09-20 13:05
That's right, this was a regression. I have been working on a patch for this, roughly ~80% done, pull request will be up soon. Closing this as duplicate, let's discuss in that other bug.
