### ISSUE TITLE
embind's std::string marshalling should use TextEncoder/TextDecoder when available

### ISSUE THREAD

**Issue by brion** [kripken/emscripten#4222] opened 2016-04-03 11:22 UTC
Per [this email thread](https://groups.google.com/forum/#!topic/emscripten-discuss/mhy4pkudm9k), marshaling of std::string values to/from JavaScript currently uses a hardcoded Latin-1<->UTF-16 conversion that also looks inefficient, doing byte-by-byte copying to tiny one-char strings and then joining an array.

This could probably use TextEncoder/TextDecoder interfaces in supporting browsers to marshal large strings more efficiently.

The relevant code is in embind.js; search for '_embind_register_std_string' and see the 'fromWireType' and 'toWireType' methods that get defined there.

Could also benefit https://github.com/kripken/emscripten/issues/4221 ?

**Comment by hackcasual** [comment] 2016-06-22 22:37
Looks like #4402  is a dupe of this

**Comment by juj** [comment] 2016-06-23 11:59
This is #4402 and #4403. TextDecoder can't be used in all cases, so the handwritten JS version will need to remain available as a fallback. You mention that the JavaScript side conversion is inefficient, so if you have a more efficient algorithm to use for that part, pull requests are welcome.

**Closed by juj** 2016-06-23 11:59 UTC
