### ISSUE TITLE
implicit declaration of function 'xyz' is invalid in C99

### ISSUE THREAD

**Issue by ChandraNakka** [kripken/emscripten#3155] opened 2015-01-28 07:10 UTC
Dear developer,

Your project is very great concept (No doubt).

But, I think `earning millions` is easier than compiling programs with emscripten (This is also no doubt).

Please look at this type of errors. `title of this issue`

I'm compiled so many programs without emscripten very successfully. But when I'm using emscripten, always I got this type of errors.

**Comment by juj** [comment] 2015-01-28 12:22
Sorry, I do not follow. Can you post a small test case showing the problem?

**Comment by ChandraNakka** [comment] 2015-01-28 13:33
@juj 

Dear friend,

Sorry, Currently I can't show any error messages to you. Because, I'm completly removed emscripten from my system and life. I don't want to re install emscripten on my system and I don't want  to waste my time with this.

Any I will challenge you. Are you ready to compile ffmpeg with libmp3lame. By latest version of emscripten, ffmpeg and lame.

I know it's impossible. :)

**Comment by juj** [comment] 2015-01-28 13:52
Apologies, but I cannot take on that challenge. While Emscripten supports some amount of drop-in compatibility with existing gcc/clang compilers, we do not claim it would be a guaranteed one-to-one replacement. Instead, you should expect that issues will undoubtedly come up, and you cannot assume that any given project will build automatically out of the box without the need of extra porting and development for the project in hand. Doing a successful port will require experience with the platforms and the project in question and knowledge to be able to debug the issues that come up in order to triage whether they are deficiencies of the project build system, the project source code, or the compiler itself.

Let me close this bug, since it lacks concrete steps to reproduce. If you decide to give it another go in the future, feel free to post bugs that clearly explain, preferably in a small test if possible, what the problem is, along with concrete steps to reproduce and verify. That will increase the chances of the bug getting answered by one of the authors or community members.

**Closed by juj** 2015-01-28 13:52 UTC

**Comment by kripken** [comment] 2015-01-28 23:18
Small addition to what @juj said, I think the specific issue based on the title here, is that we give an error by default on something that is undefined behavior and that clang warns on. It's easy to change that to a warning, however, it's not recommended, as in emscripten this undefined behavior is much more dangerous. Undefined behavior like this is definitely an area in which developers need to be careful when porting to new targets.

**Comment by mchiasson** [comment] 2017-03-08 20:08
```
ufile.c:53:23: error: implicit declaration of function 'fileno' is invalid in C99
```
looks like changing `-std=c99` to `-std=gnu99` got rid of that issue though.
