### ISSUE TITLE
Exception sometimes not caught

### ISSUE THREAD

**Issue by Quiark** [kripken/emscripten#4041] opened 2016-01-15 02:27 UTC
I ran into this issue where I throw an exception in my unit test and the TDD framework will catch it because it's expected. With emscripten, the exception did not get caught. When I added a printf() statement inside the `try {}` block before the throwing call, suddenly it got caught correctly. Native build using clang always catches the exception.

Here is the minimal test case https://gist.github.com/Quiark/7924bfc88c0f1d9a8aad

It contains the TDD framework called Catch (https://github.com/philsquared/Catch) with some modifications I made to simplify the bug. Search for the macro `INTERNAL_CATCH_THROWS_AS`. The other file, `run.cpp` is just a demonstration of how I use it so that it exhibits the problem. There's also a compile script that you can use to build the sample both with `g++` and `emcc`. Run the test with parameter `[blah]` which will select the single test case for running.

My environment:
OSX 10.10.5
Emscripten installed using homebrew 
```
roman@Amanda ~/A/A/bug_sample> emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.35.9
clang version 3.8.0  (emscripten 1.35.9 : 1.35.9)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
INFO:root:(Emscripten: Running sanity checks)
```

In catch.hpp line 1650, I call `clock()` function in an else branch. Originally the framework had a different call there. If I remove the else branch completely, the bug does not exhibit. If there is a call, however, the bug appears. It's pretty random :)

**Comment by kripken** [comment] 2016-01-15 04:41
I can confirm different output from native. However,

1. I had to modify the compile script to remove `test/` in all places. Probably doesn't matter, but it means I'm not running exactly what you are.
2. I had to remove `-m64` from the native build as i'm on 32-bit, another difference.
3. I see different flags passed to the native and JS build, e.g. `-DUSE_OSSL`.

Assuming all of those are not an issue, then this does look like a bug of some sort. It would really be useful to get a minimal test case, though - `catch.hpp` has almost 10,000 lines.

**Comment by Quiark** [comment] 2016-01-15 06:04
Updated the gist compile script https://gist.github.com/Quiark/7924bfc88c0f1d9a8aad.

Currently too busy to try to get catch.hpp smaller though. It definitely behaves like a bug because it behaves rather randomly, just try to make the change in `INTERNAL_CATCH_THROWS_AS` as described, it will suddenly start behaving correctly.

**Comment by waywardmonkeys** [comment] 2016-01-15 06:40
With some effort and/or pain, LLVM's bugpoint might help minimize the test case.

**Comment by Quiark** [comment] 2016-01-19 03:21
I'm going to try to minimize it a bit further.

**Comment by Quiark** [comment] 2016-01-19 04:20
Removed the Catch library, this sample is much smaller:
https://gist.github.com/Quiark/7924bfc88c0f1d9a8aad

Note that removing the member `m_assertionInfo` from the class `Before` will change the program behaviour, it will start to catch the exception properly.

**Comment by waywardmonkeys** [comment] 2016-01-19 05:59
That seems interesting. What I'd do here since the code change between working and not working is relatively small is to debug the generated JS (no sourcemaps) for the working vs non-working cases.

**Comment by waywardmonkeys** [comment] 2016-01-19 06:01
Too bad the old branch-debugging code isn't around still! :)

You want to see where control flow or something else differs between the two ... you might even be able to hand-edit the generated JS to look for and minimize differences to further narrow it down based on debugging both versions.

**Comment by kripken** [comment] 2016-01-20 00:17
Ok, this looks like a bug in the lowering of exceptions - bad interactions with simplifyCFG. Looking into a fix now.

**Comment by kripken** [comment] 2016-01-20 00:56
Ok, fixed on incoming.

Thanks for the reduced testcase! :)

**Closed by kripken** 2016-01-20 00:56 UTC

**Comment by Quiark** [comment] 2016-01-20 03:18
Thanks :)
