### ISSUE TITLE
emcc went missing on windows

### ISSUE THREAD

**Issue by kg** [kripken/emscripten#3389] opened 2015-04-22 20:35 UTC
Managed to successfully emsdk install and emsdk activate on this machine after working around previous bug reports. When I invoke emcc on this machine to compile scripts, it fails:

```
>emcc -O0 -s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 test.cpp
python: can't open file 'C:\PF\Emscripten\emscripten\incoming\\emcc': [Errno 2] No such file or directory
```

I've checked and emcc.bat and emcc.py are in that folder but there's no extension-less 'emcc'. Any ideas?

**Comment by kg** [comment] 2015-04-22 20:36
Changing emcc.bat to
```python
python "%~dp0\emcc.py" %*
```
seems to fix this. It was ```"%~dp0\emcc"``` before.

**Comment by kg** [comment] 2015-04-22 21:06
I take that back, it seems like that fix just makes emcc terminate silently.

**Comment by kg** [comment] 2015-04-22 21:14
My 1.29.0 folder from the SDK install contains an 'emcc' file containing actual emcc; my incoming folder does not.

**Comment by kg** [comment] 2015-04-22 21:16
```
C:\PF\Emscripten\emscripten\incoming>git status
On branch incoming
Your branch is up-to-date with 'origin/incoming'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    emcc
```
Not sure how that happened. I definitely didn't do it. ```emsdk install sdk-incoming-64bit``` doesn't notice this or correct it.

**Comment by juj** [comment] 2015-04-23 07:28
No idea how this can happen. If you can come up with steps to reproduce, that would be useful.

**Comment by Zelif** [comment] 2015-04-23 15:37
Just did a fresh install on a laptop(win8) having the same problem with 1.3
emcc command doesn't work.

**Comment by Azaril** [comment] 2017-06-11 22:44
This appears to be caused by the expansion of the %~dp0 in emcc.bat resolving to the wrong directory instead of the directory emcc.bat is running in.

I locally worked around this by changing the batch file contents to:
``
@echo off
python "%EMSCRIPTEN%\emcc.py" %*
``
This could be caused by how the batch file is invoked - in my case I'm using rust with a compilation target of emscripten.

**Comment by juj** [comment] 2017-06-12 09:27
Reading https://stackoverflow.com/questions/5034076/what-does-dp0-mean-and-how-does-it-work it does look like `%0` expands to the current executable, so if that goes wrong due to some odd way of subprocess spawning, then I'd recommend that such subprocess spawns would directly spawn `python emcc`.

**Comment by juj** [comment] 2017-06-12 10:06
Actually, rereading, I'm not sure if @Azaril 's observation above is the same root cause as @kg 's. However this bug is quite old, and we haven't had similar reports anymore, so I'll close this one. If the issue does not seem to be resolvable on Rust's side, let's discuss that further in a new bug report.

**Closed by juj** 2017-06-12 10:06 UTC

**Comment by dten** [comment] 2017-06-29 19:33
I've just been running into this and had to change `emcc.bat` to as @Azaril suggested otherwise i get 

```
 note: python: can't open file 'C:\d\Documents\Repositories\\gameboyemulator\gameboy-ng\src\test-rs\\emcc': [Errno 2] No such file or directory
```

**Comment by phoenixx2** [comment] 2018-07-31 19:14
Running into the same issue here.  Given 5 participants and several thumbs up on the same solution, why isn't the batch file changed in general so everyone can benefit from such a fix?  Though to be clear, %EMSCRIPTEN% was set to an older version, so the specified fix is far from universal.
