### ISSUE TITLE
No compile time error is issued if a JS library function depends on a nonexisting symbol.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#4077] opened 2016-02-04 20:12 UTC
STR: With `library_foo.js` as

	mergeInto(LibraryManager.library, {
	  my_js__deps: ['nonexistingvariable'],
	  my_js: (function() {
	      return function() {
	        console.log("hello " + _nonexistingvariable);
	      };
	  }()),
	});

and `foo.cpp` as

	#include<stdio.h>
	#include<stdlib.h>

	extern "C" {
	  extern void my_js();
	}

	int main() {
	  my_js();
	  return EXIT_SUCCESS;
	}

Build with `emcc --js-library library_foo.js  foo.cpp -o a.js` will finish without errors or warnings, and running it will print

	C:\code\emsdk\emscripten\incoming>node a.js
	hello undefined

It would be better to issue a linker error "Undefined symbol: 'nonexistingvariable' as a dependency of function 'my_js' in file library_foo.js"?

**Comment by kripken** [comment] 2016-02-04 22:04
Yeah, this looks wrong, I'll look into fixing it.

**Comment by kripken** [comment] 2016-02-04 23:36
So the issue is #2154 - this can produce false positives. But, fixable, doing it now.

**Comment by kripken** [comment] 2016-02-05 01:15
Fixed on incoming.

**Closed by kripken** 2016-02-05 01:15 UTC
