### ISSUE TITLE
Unresolved symbol for duplicated file names V2

### ISSUE THREAD

**Issue by mad-rain** [kripken/emscripten#3196] opened 2015-02-16 12:38 UTC
Hi!

I have recently updated Emscripten from 1.27.0 to 1.29.0 and can't link my project now.

To reproduce this you need to create 3 files:

1) Main.cpp

```
extern void Func1();

extern void Func2();

int main()
{
	Func1();

	Func2();

 	return 0;
}
```

2) File.cpp

```
#include <stdio.h>

void Func2()
{
	printf("Func2\n");
}
```

3) Dir/File.cpp
```

#include <stdio.h>

void Func1()
{
	printf("Func1\n");
}
```

And then compile & link them:

em++ -c File.cpp -o File.o
em++ -c Dir/File.cpp -o Dir/File.o
em++ rc libLib.a File.o Dir/File.o
em++ Main.cpp libLib.a -o application.html

You will get the following error:
```
warning: unresolved symbol: _Z5Func2v
```

**Comment by kripken** [comment] 2015-02-20 21:38
Looks like a duplicate of #2619

**Closed by kripken** 2015-02-20 21:38 UTC
