### ISSUE TITLE
Global variables are not correctly aligned.

### ISSUE THREAD

**Issue by juj** [kripken/emscripten#3561] opened 2015-06-19 16:33 UTC
When using the `__attribute__((aligned(16)))` attribute, or the LLVM vector attribute `typedef float float32x4 __attribute__((__vector_size__(16), __may_alias__))` to specify 16-byte alignment for a variable, global variables should get this alignment, but testing on the following code, it looks like 8 byte alignment is the best that is achieved. The following code

	#include <xmmintrin.h>
	#include <stdio.h>

	struct __attribute__((aligned(16))) float4x4
	{
		union
		{
			float v[4][4];
			__m128 row[4];
		};
	};

	float4x4 v;
	__m128 m;

	int main()
	{
		printf("Alignment: %d addr: %x\n", ((int)&v) % 16, (int)&v);
		printf("Alignment: %d addr: %x\n", ((int)&m) % 16, (int)&m);
	}

prints

    Alignment: 8 addr: 8
    Alignment: 8 addr: 48

when it is expected to print `Alignment 0`. Function local variables seem to work ok. I see we get the global address `8` as the starting address, perhaps this has to do with a guardband address of 8 bytes at the start of the heap (or similar?), and that should be bumped to 16 bytes or more? @kripken?

**Comment by kripken** [comment] 2015-06-19 22:30
The issue is that we just assume align 8 for all heap vars, which was a temporary thing that... never stopped working, so we never fixed it ;)

I opened `heapalign` branches to fix this. I think I have most of the logic done, but still some test failures currently.

**Comment by kripken** [comment] 2015-06-25 00:24
Ok, I have a fix for this. Pushing now.

This fixes this testcase, and also shrinks mem init files, e.g. BananaBread's by 2.5%, mainly because we used to align all the small strings to 8 bytes, but no longer do.

This found one case of undefined behavior in the test suite. It's possible this will regress existing codebases that have undefined behavior, but I don't think that should stop this.

**Comment by kripken** [comment] 2015-06-25 18:45
Looks ok on bots.

**Closed by kripken** 2015-06-25 18:45 UTC
Labels: SIMD
