### ISSUE TITLE
ALLOW_MEMORY_GROWTH not working with USE_PTHREADS=1

### ISSUE THREAD

**Issue by thomasjammet** [kripken/emscripten#7110] opened 2018-09-11 08:22 UTC
I don't know if this behavior is expected but every time I set USE_PTHREADS=1 ALLOW_MEMORY_GROWTH=1 and WASM_MEM_MAX are ignored.

You can reproduce the issue by compiling [test_memorygrowth_wasm_mem_max.c](https://github.com/kripken/emscripten/blob/incoming/tests/core/test_memorygrowth_wasm_mem_max.c) with the following command :

```
emcc .\test_memorygrowth_wasm_mem_max.c -s USE_PTHREADS=1 -s TOTAL_ME
MORY=64Mb -s ALLOW_MEMORY_GROWTH=1 -s WASM_MEM_MAX=100Mb -o testmem.html
```

**Comment by MarcelKlammer** [comment] 2018-09-19 20:04
preamble.js generates this:

```
function enlargeMemory() {
  abort('Cannot enlarge memory arrays, since compiling with pthreads support enabled (-s USE_PTHREADS=1).');
}
```

**Comment by dschuff** [comment] 2018-09-19 20:48
I'm guessing this is an intentional limitation left over from before wasm threads support was added (i.e. when only asm.js was supported). For wasm, resizing is allowed; the [requirement](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#resizing) is that the max memory size must be specified (instead of being left unspecified, which places no limit on growth up to 4GB). Probably I just never got around to making that behavior correct when I added the initial wasm threads support. So `WASM_MEM_MAX` should work, and we should should require it to be specified if `ALLOW_MEMORY_GROWTH=1`. I (or someone) will hopefully fix this soon, otherwise I'd be happy to review a PR :)

**Comment by wffurr** [comment] 2019-01-09 15:17
This is blocked on work in v8 and other browsers.  See https://github.com/kripken/emscripten/issues/7382 for the full discussion.

This issue should probably be marked as a duplicate.

**Comment by kripken** [comment] 2019-01-09 17:43
Thanks @wffurr, yeah, looks like all the details are in the other issue, so let's close this as a duplicate of it.

**Closed by kripken** 2019-01-09 17:43 UTC
Labels: help wanted
