### ISSUE TITLE
Move uint8_t declarations into Uint8Array, not Int32Array

### ISSUE THREAD

**Issue by 18kaioken** [kripken/emscripten#4824] opened 2016-12-29 18:02 UTC
Hi... I'm still beginner in both C and C++. I was inspecting the emcc -O3 output from this test code:

```c++
#include <iostream>
//#include "inc.h"

int main() {
//for (unsigned short i = 0; i < 10; ++i)
//    test();
  uint8_t Ana = 151, bb = 20, cc = 18, dd = 150;
  //std::cout << i << std::endl;
  printf("%u", Ana);
}
```

When I repair the output code, I guess I see an `Int32Array` property being setted with this `151` value (which is the unique used above):

```c++
function Ka(){var a=0,b=0;a=i;i=i+16|0;b=a;

/* This 'c' looks to be an `Int32Array` (I've found a hoisted variable declaration with `c` initializing with an `Int32Array`). */
c[b>>2]=151;

Ua(672,b)|0;i=a;return 0}
```

This is the compressed output (using -O3 option). I think the correct collection to put the `151` value is at `d`, according to the compressed output:

```C++
var d=new global.Uint8Array(buffer); // That's what I see in the compressed output.
```

Can you fix dis? Thanks!

**Comment by kripken** [comment] 2017-01-03 19:03
It's very hard to read minified output - that could just be another 151 from something else. I would look at unminified code (-O0 or -O1). Otherwise, if the code executes ok, then it's probably fine.

**Comment by hydroper** [comment] 2017-01-03 19:39
Yeah! Sorry about that, but that `151` it the last one found in the minified output. There's not any `151` besides that.

**Comment by kripken** [comment] 2017-01-04 19:08
It's possible LLVM assigns it a 32-bit stack slot anyhow, even though it's 8 bits. Possibly looking at the LLVM IR might help clarify things.

**Comment by 18kaioken** [comment] 2017-08-24 18:06
@kripken Not sure what you meant. Though, will `uint8_t` continue to be an `int32_t` internally?

**Comment by juj** [comment] 2017-08-24 18:34
The footgun here is that varargs ABI rules in C language say that 8 and 16 bit integers are passed as int32s. For calling `printf` it is required to expand the `uint8_t` variable above to 32 bit. Same occurs even if you printed, say a `%c` for a character. In Emscripten/asm.js/wasm, `uint8_t` is not a `int32_t` internally, but a `uint8_t`. I'll close this as not a bug.

**Closed by juj** 2017-08-24 18:34 UTC
