### ISSUE TITLE
how do you install a previous version of the sdk?

### ISSUE THREAD

**Issue by mlogan** [kripken/emscripten#3482] opened 2015-05-30 00:09 UTC
[apologies if this belongs in https://github.com/juj/emsdk, but there's very little activity there]

We're having some problems with 1.33.0 - it's probably our fault, so I'm not filling a bug for that until I've had more time to dig into it.

In the meantime, we need to be able to do the equivalent of `emsdk install sdk-1.32.0-64bit` to get our continuous build working. I've spent 30 minutes or so searching the docs and trying various `emsdk` incantations, and I can't actually figure out how to do this seemingly obvious task.

**Comment by evanw** [comment] 2015-05-30 18:46
It's unfortunate that the SDK doesn't do versioning well since that's kind of the point of an SDK. I've had this issue [in the past](https://github.com/kripken/emscripten/issues/3022), but I worked around it by building [my own "SDK"](https://gist.github.com/evanw/e5aa506a31a5dfbd807e) that handles versions. It has to install LLVM itself which is pretty slow but we've been using it for many months and it's been working fine. Hope that helps.

**Comment by kripken** [comment] 2015-05-30 19:05
cc @juj

**Comment by juj** [comment] 2015-06-01 07:05
This is duplicate of https://github.com/juj/emsdk/issues/34.

**Closed by juj** 2015-06-01 07:05 UTC
Labels: emsdk
